### ISSUE TITLE
rbenv + doom emacs + zsh

### ISSUE THREAD

**Issue by idoo** [hlissner/doom-emacs#1068]
### Observed behavior
I switched to ohmyzsh and curretly I have rbenv + .ruby-version file in repo
When I'm opening console in the shell I can see correct version of ruby
But doom emacs shows another version

looks like the same issue with fish shell as well

### Expected behavior
see the same version as in zsh/fish console

**Comment by azy2** [comment]
This is because you are launching emacs from your desktop environment which doesn't have the same environment variables as your shell. Emacs inherits it's environment variables from wherever it's launched. As an experiment try opening a zsh (or fish) shell with the correct rbenv settings and then launching emacs. Does it have the correct version now? If it does here's one way you get those variables into instances launched from your desktop:

Get the following package: `(package! exec-path-from-shell)`

and then configure it to grab what you need:
```
(when (memq window-system '(mac ns x))
  (require 'exec-path-from-shell)
  (setq-default exec-path-from-shell-shell-name "/usr/bin/zsh")
  (exec-path-from-shell-copy-env "RUST_SRC_PATH")
(exec-path-from-shell-initialize))
```
This will copy the PATH variable from zsh and it will also copy "RUST_SRC_PATH" from zsh. Hopefully you can figure out which variables you need.

**Comment by hlissner** [comment]
While exec-path-from-shell will work, if you're on mac, Doom is already using it.

A common reason Emacs isn't picking up these envvars is that they (e.g. `PATH` and/or `RUST_SRC_PATH`) are configured in `~/.zshrc` (read in interactive sessions) rather than `~/.zshenv` (non-interactive sessions). App launchers tend to spawn processes from a non-interactive session.

For rbenv, specifically, I believe the best way would be to move your `rbenv init` to `~/.zshenv`. Same goes for any envvars you think should be visible globally.

If that is too slow, try `rbenv init - --no-rehash` instead.

Here is what I use to ensure it has minimal impact on shell init time:

```sh
function _cache {
  local cache_dir="${XDG_CACHE_HOME:-~/.local/share}/${SHELL##*/}"
  local cache="$cache_dir/$1"
  if [[ ! -f $cache || ! -s $cache ]]; then
    echo "Caching $1"
    mkdir -p $cache_dir
    "$@" >$cache
  fi
  source $cache
}

_cache rbenv init - --no-rehash
```

**Comment by idoo** [comment]
@hlissner btw, described case happens on Mac

**Comment by idoo** [comment]
for some reason, it still requires `rvm`

`rspec-compile: Symbol’s function definition is void: rvm-activate-corresponding-ruby`

and I still didn't get why by default it execute `fish` instead of `zsh` ?

**Comment by eltone** [comment]
I fixed the above error with the following config
```
(after! rspec-mode
  (setq rspec-use-rvm nil))
```

**Comment by hlissner** [comment]
@idoo Sorry for the late reply. Does @eltone's snippet work for you?

**Comment by idoo** [comment]
not really :( I still have wrong ruby version :(

**Comment by wontruefree** [comment]
I am also having the problem.

**Comment by thdaraujo** [comment]
For those that are still having problems with this (I'm on MacOS Ventura):

I was able to fix it by [following this suggestion and adding RBENV_ROOT to .zshenv](https://github.com/rbenv/rbenv/issues/1508#issuecomment-1600531709).

```sh
# on ~/.zshenv

export RBENV_ROOT="$HOME/.rbenv"
export PATH="$HOME/.rbenv/shims:${PATH}"
```

```sh
# on ~/.zshrc

eval "$(rbenv init - zsh)"
```

This fixed `ruby-mode` for me. 🙌 

You can also add the `no-rehash` option if you want to: `rbenv init - zsh --no-rehash`.

-- 

If you'd like to follow [the previous suggestion](https://github.com/doomemacs/doomemacs/issues/1068#issuecomment-452029550), you might need to set `XDG_CACHE_HOME` as well:

```sh
# set cache home on MacOS
export XDG_CACHE_HOME="$HOME/Library/Caches"

function _cache {
... etc

```
