### ISSUE TITLE
[BUG] PDF module does not work out of the box

### ISSUE THREAD

**Issue by benjaminbauer** [hlissner/doom-emacs#1788]
**Describe the feature**
The `pdf` module should call `pdf-tool-install` during the installation of the module as advised [here](https://github.com/politza/pdf-tools/issues/288). Otherwise PDFs wont open properly in doom.

**Comment by benjaminbauer** [comment]
Hm, I just saw https://github.com/hlissner/doom-emacs/commit/4f7bf8b976f88d08a62c40e5b605a51876676fb9

So is there a workaround? Maybe `doom doc` could warn the user that he/she has to run `pdf-tool-install` manually?

**Comment by hlissner** [comment]
After some experimenting, I found a way to reliably pull it off. As of fccafff epdfinfo is once again built when pdf-tools is first loaded, which should resolve this issue. Let me know if that isn't the case and I'll reopen it.

Thanks for bringing it to my attention!

**Comment by AethanFoot** [comment]
Sorry to open an old thread but this issue is relevant, after updating I needed to rebuild epdfinfo each time with with the warning to build it. I ran pdf-tools-install which permanently built it, but each time I open a pdf I still get the warning to build it (it loads instantly as it is already built, just gives a warning every time).

**Comment by hlissner** [comment]
@AethanFoot fixed in f11979e

**Comment by AethanFoot** [comment]
Awesome, works great.
