### ISSUE TITLE
[BUG] org-mode TAB key mapped to different command when emacs running as daemon

### ISSUE THREAD

**Issue by h7zhang** [hlissner/doom-emacs#1897]
When emacs is running as daemon, the TAB key in org mode buffer is mapped to bettter-jumper-jump-forward. When emacs is running standalone, either tty or GUI, the TAB key is mapped to org-cycle.

 

**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2")
  (build . "Sep 13, 2019")
  (buildopts "--prefix= --prefix=/snap/emacs/current/usr 'CFLAGS= -I/build/emacs/parts/emacs/install/usr/include' 'CPPFLAGS= -I/build/emacs/parts/emacs/install/usr/include' 'LDFLAGS= -L/build/emacs/parts/emacs/install/lib -L/build/emacs/parts/emacs/install/usr/lib -L/build/emacs/parts/emacs/install/lib/x86_64-linux-gnu -L/build/emacs/parts/emacs/install/usr/lib/x86_64-linux-gnu'")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD b343f238f 2019-10-13 00:28:48 -0400"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64")
  (path "~/bin" "~/.toolbox/bin"  "~/.cargo/bin" "~/.emacs.d/bin"  "~/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin"  "/snap/bin" "/snap/emacs/current/usr/libexec/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs dired electric vc :tools eval flycheck (lookup +docsets) magit :lang data emacs-lisp markdown (org +dragndrop +ipython +pandoc +present) sh :config (default +bindings +smartparens))
  (packages "n/a")
  (elpa "n/a")))

</pre></details>

**Comment by hlissner** [comment]
This is really an [evil-org-mode](https://github.com/Somelauw/evil-org-mode) issue. There appears to be an issue open for it: https://github.com/Somelauw/evil-org-mode/issues/54.

It only binds `org-cycle` to `(kbd "<tab>")` (i.e. `[tab]`), which is the input event that gui emacs triggers. Terminal Emacs triggers `(kbd "TAB")` (i.e. `"\t"`), but evil-org has no keybind for it.

Please chime into Somelauw/evil-org-mode#54. I've resolved this temporarily, in Doom, but will keep this open until I know for sure it has been (or won't be) addressed upstream.

**Comment by h7zhang** [comment]
Thanks for the prompt response. So In the mean time, before the bug is fixed in upstream, I just put these lines in my private config.el to make org usable in daemon:

<pre>
;; Patch up the evil-org key map, so that org is usable with daemon
;; https://github.com/hlissner/doom-emacs/issues/1897
(after! evil-org
  (evil-define-key '(normal visual) evil-org-mode-map
    (kbd "TAB") 'org-cycle))
</pre>

**Comment by hlissner** [comment]
I've already fixed this in 25acbd2. If you are unable to update, then yes, your code will work.

**Comment by randomizedthinking** [comment]
I encountered the same issue today. With solution provided by @h7zhang, it is fine for now.

@hlissner, seems the latest commit triggers the issue back.

**Comment by hlissner** [comment]
@randomizedthinking As of fb28586 we've switched to a fork of `evil-org` which resolves these issues. At the moment, Doom's package manager cannot see recipe changes, so you will need to manually delete `~/.emacs.d/.local/straight/{repos,build}/evil-org`, as well as `~/.emacs.d/.local/straight/build-cache.el`, then run `doom refresh -f` to get Doom to install it with the new recipe.

**Comment by randomizedthinking** [comment]
Thanks a bunch for your hard work!

**Comment by randomizedthinking** [comment]
@hlissner I followed the instruction, and it worked out nicely yet with one issue: the org-agenda still does not work properly. So in addition, we need to manually delete `org` folder as well:

    rm -rf ~/.emacs.d/.local/straight/{repos,build}/org
    rm -rf ~/.emacs.d/.local/straight/{repos,build}/evil-org
    doom refresh -f
