### ISSUE TITLE
Doom installation hangs on org-plus-contrib

### ISSUE THREAD

**Issue by tamasgal** [hlissner/doom-emacs#2409]
**What did you expect to happen?**

The installation of Doom emacs should work.

**What actually happened?**

The installation of Doom emacs (`doom install`) hangs for a couple of minutes while installing `org-plus-contrib` and ultimately exits, recommending to rerun with `doom -d install` and report the output if the problem persists.

I deleted `~/.emacs.d` and rerun `doom install` a few times but it did not help.

**Additional details:**
- Include a link to your private config: https://github.com/tamasgal/rc/tree/master/doom.d

Initial warning:

<details><pre>
  → Cloning evil-markdown...done
  → Building evil-markdown...
  → Building evil-markdown...done
  → Cloning org (for org-plus-contrib)...
x There was an unexpected error:
  Type: doom-package-error
  Message:
    Error with packages
  Data:
    "org-plus-contrib"
    (error "Failed to run \"git\"; see buffer *straight-process*")
    "Cloning into '/Users/tamasgal/.emacs.d/.local/straight/repos/org'...
    fatal: https://code.orgmode.org/bzg/org-mode.git/info/refs not valid: is this a git repository?
    "
  Straight output:
    Cloning into '/Users/tamasgal/.emacs.d/.local/straight/repos/org'...
    fatal: https://code.orgmode.org/bzg/org-mode.git/info/refs not valid: is this a git repository?

Run the command again with the -d (or --debug) switch to enable debug
mode and (hopefully) generate a backtrace from this error:

  doom -d install

If you file a bug report, please include it!
</pre></details>

Detailed trace:

<details><pre>
DOOM Pinning package "emacs-python-pytest" to "09ad688df207ee9b02c990d3897a9e2841931d97"
DOOM Pinning package "pyimport" to "a6f63cf7ed93f0c0f7c207e6595813966f8852b9"
DOOM Pinning package "py-isort.el" to "e67306f459c47c53a65604e4eea88a3914596560"
DOOM Pinning package "sphinx-mode" to "b5ac514e213459dcc57184086f10b5b6be3cecd8"
DOOM Pinning package "company-shell" to "52f3bf26b74adc30a275f5f4290a1fc72a6876ff"
DOOM Pinning package "emacs-calfw" to "03abce97620a4a7f7ec5f911e669da9031ab9088"
DOOM Pinning package "emacs-calfw" to "03abce97620a4a7f7ec5f911e669da9031ab9088"
DOOM Pinning package "org-gcal.el" to "6821e349673e9ba8d7ae7b84789f931889273dc0"
DOOM Pinning package "drag-stuff.el" to "6d06d846cd37c052d79acd0f372c13006aa7e7c8"
DOOM Pinning package "link-hint.el" to "8d8f9505f87dc8a3b3baee7cb516f091072893a7"
- Envvar file already exists, skipping
Installing plugins
> Installing & building packages...
  → Cloning org (for org-plus-contrib)...

...
  (let ((recipe (straight--convert-recipe (or (straight--get-overridden-recipe (if (listp melpa-style-recipe) (car melpa-style-recipe) melpa-style-recipe)) melpa-style-recipe) cause))) (straight--register-recipe recipe) (let* ((plist recipe) (package (plist-get plist :package)) (local-repo (plist-get plist :local-repo)) (type (plist-get plist :type))) (if (eq type (quote built-in)) (progn (throw (quote --cl-block-straight-use-package--) t))) (straight--transaction-exec (intern (format "use-package-%S-%S-%S" recipe (if (let (...) (and ... ...)) (random) no-clone) (if (let (...) (and ... ...)) (random) no-build))) :now (function (lambda nil (let ((already-registered ...) (available ...)) (if (if ... ... no-clone) (progn ...)) (if available nil (straight--clone-repository recipe cause)) (straight--make-build-cache-available) (let* (... ...) (let ... ...) (if no-build nil ...) (run-hook-with-args ... package) (if ... ...) (straight--declare-successful-build recipe) (if no-build nil ... ... ...) (if ... ...)) (puthash package t straight--success-cache) t))))))
  (catch (quote --cl-block-straight-use-package--) (let ((recipe (straight--convert-recipe (or (straight--get-overridden-recipe (if ... ... melpa-style-recipe)) melpa-style-recipe) cause))) (straight--register-recipe recipe) (let* ((plist recipe) (package (plist-get plist :package)) (local-repo (plist-get plist :local-repo)) (type (plist-get plist :type))) (if (eq type (quote built-in)) (progn (throw (quote --cl-block-straight-use-package--) t))) (straight--transaction-exec (intern (format "use-package-%S-%S-%S" recipe (if (let ... ...) (random) no-clone) (if (let ... ...) (random) no-build))) :now (function (lambda nil (let (... ...) (if ... ...) (if available nil ...) (straight--make-build-cache-available) (let* ... ... ... ... ... ... ... ...) (puthash package t straight--success-cache) t)))))))
  (closure (straight--profile-cache use-package-pre-ensure-function use-package-keywords use-package-ensure-function use-package-defaults t) (melpa-style-recipe &optional no-clone no-build cause interactive) "Register, clone, build, and activate a package and its dependencies.\nThis is the main entry point to the functionality of straight.el.\n\nMELPA-STYLE-RECIPE is either a symbol naming a package, or a list\nwhose car is a symbol naming a package and whose cdr is a\nproperty list containing e.g. `:type', `:local-repo', `:files',\nand VC backend specific keywords.\n\nFirst, the package recipe is registered with straight.el. If\nNO-CLONE is a function, then it is called with two arguments: the\npackage name as a string, and a boolean value indicating whether\nthe local repository for the package is available. In that case,\nthe return value of the function is used as the value of NO-CLONE\ninstead. In any case, if NO-CLONE is non-nil, then processing\nstops here.\n\nOtherwise, the repository is cloned, if it is missing. If\nNO-BUILD is a function, then it is called with one argument: the\npackage name as a string. In that case, the return value of the\nfunction is used as the value of NO-BUILD instead. In any case,\nif NO-BUILD is non-nil, then processing halts here. Otherwise,\nthe package is built and activated. Note that if the package\nrecipe has a non-nil `:no-build' entry, then NO-BUILD is ignored\nand processing always stops before building and activation\noccurs.\n\nCAUSE is a string explaining the reason why\n`straight-use-package' has been called. It is for internal use\nonly, and is used to construct progress messages. INTERACTIVE is\nnon-nil if the function has been called interactively. It is for\ninternal use only, and is used to determine whether to show a\nhint about how to install the package permanently.\n\nReturn non-nil if package was actually installed, and nil\notherwise (this can only happen if NO-CLONE is non-nil)." (interactive (list (straight-get-recipe (if current-prefix-arg (progn (quote interactive)))) nil nil nil (quote interactive))) (catch (quote --cl-block-straight-use-package--) (let ((recipe (straight--convert-recipe (or (straight--get-overridden-recipe ...) melpa-style-recipe) cause))) (straight--register-recipe recipe) (let* ((plist recipe) (package (plist-get plist :package)) (local-repo (plist-get plist :local-repo)) (type (plist-get plist :type))) (if (eq type (quote built-in)) (progn (throw (quote --cl-block-straight-use-package--) t))) (straight--transaction-exec (intern (format "use-package-%S-%S-%S" recipe (if ... ... no-clone) (if ... ... no-build))) :now (function (lambda nil (let ... ... ... ... ... ... t))))))))(org-plus-contrib nil nil " " nil)
  apply((closure (straight--profile-cache use-package-pre-ensure-function use-package-keywords use-package-ensure-function use-package-defaults t) (melpa-style-recipe &optional no-clone no-build cause interactive) "Register, clone, build, and activate a package and its dependencies.\nThis is the main entry point to the functionality of straight.el.\n\nMELPA-STYLE-RECIPE is either a symbol naming a package, or a list\nwhose car is a symbol naming a package and whose cdr is a\nproperty list containing e.g. `:type', `:local-repo', `:files',\nand VC backend specific keywords.\n\nFirst, the package recipe is registered with straight.el. If\nNO-CLONE is a function, then it is called with two arguments: the\npackage name as a string, and a boolean value indicating whether\nthe local repository for the package is available. In that case,\nthe return value of the function is used as the value of NO-CLONE\ninstead. In any case, if NO-CLONE is non-nil, then processing\nstops here.\n\nOtherwise, the repository is cloned, if it is missing. If\nNO-BUILD is a function, then it is called with one argument: the\npackage name as a string. In that case, the return value of the\nfunction is used as the value of NO-BUILD instead. In any case,\nif NO-BUILD is non-nil, then processing halts here. Otherwise,\nthe package is built and activated. Note that if the package\nrecipe has a non-nil `:no-build' entry, then NO-BUILD is ignored\nand processing always stops before building and activation\noccurs.\n\nCAUSE is a string explaining the reason why\n`straight-use-package' has been called. It is for internal use\nonly, and is used to construct progress messages. INTERACTIVE is\nnon-nil if the function has been called interactively. It is for\ninternal use only, and is used to determine whether to show a\nhint about how to install the package permanently.\n\nReturn non-nil if package was actually installed, and nil\notherwise (this can only happen if NO-CLONE is non-nil)." (interactive (list (straight-get-recipe (if current-prefix-arg (progn (quote interactive)))) nil nil nil (quote interactive))) (catch (quote --cl-block-straight-use-package--) (let ((recipe (straight--convert-recipe (or ... melpa-style-recipe) cause))) (straight--register-recipe recipe) (let* ((plist recipe) (package (plist-get plist :package)) (local-repo (plist-get plist :local-repo)) (type (plist-get plist :type))) (if (eq type (quote built-in)) (progn (throw ... t))) (straight--transaction-exec (intern (format "use-package-%S-%S-%S" recipe ... ...)) :now (function (lambda nil ...))))))) (org-plus-contrib nil nil " " nil))
  straight-use-package(org-plus-contrib)
  (and (straight-use-package (intern package)) (not existed-p) (file-directory-p (straight--repos-dir (or local-repo package))) (let* ((commit (and t (cdr (assoc (or local-repo package) versions-alist))))) (if commit (progn (doom--format-print (doom--format (format (doom--format-class ... "Checking out %s commit %s") package (substring commit 0 7)))) (if (straight-vc-commit-present-p recipe commit) nil (straight-vc-fetch-from-remote recipe)) (straight-vc-check-out-commit recipe commit) t) t)) (setq n (1+ n)))
  (condition-case e (and (straight-use-package (intern package)) (not existed-p) (file-directory-p (straight--repos-dir (or local-repo package))) (let* ((commit (and t (cdr (assoc ... versions-alist))))) (if commit (progn (doom--format-print (doom--format (format ... package ...))) (if (straight-vc-commit-present-p recipe commit) nil (straight-vc-fetch-from-remote recipe)) (straight-vc-check-out-commit recipe commit) t) t)) (setq n (1+ n))) ((debug error) (signal (quote doom-package-error) (list package e (straight--process-get-output)))))
  (let ((existed-p (file-directory-p (straight--repos-dir package)))) (condition-case e (and (straight-use-package (intern package)) (not existed-p) (file-directory-p (straight--repos-dir (or local-repo package))) (let* ((commit (and t (cdr ...)))) (if commit (progn (doom--format-print (doom--format ...)) (if (straight-vc-commit-present-p recipe commit) nil (straight-vc-fetch-from-remote recipe)) (straight-vc-check-out-commit recipe commit) t) t)) (setq n (1+ n))) ((debug error) (signal (quote doom-package-error) (list package e (straight--process-get-output))))))
  (let* ((plist recipe) (package (plist-get plist :package)) (local-repo (plist-get plist :local-repo))) (let ((existed-p (file-directory-p (straight--repos-dir package)))) (condition-case e (and (straight-use-package (intern package)) (not existed-p) (file-directory-p (straight--repos-dir (or local-repo package))) (let* ((commit (and t ...))) (if commit (progn (doom--format-print ...) (if ... nil ...) (straight-vc-check-out-commit recipe commit) t) t)) (setq n (1+ n))) ((debug error) (signal (quote doom-package-error) (list package e (straight--process-get-output)))))))
  (straight--with-plist recipe (package local-repo) (let ((existed-p (file-directory-p (straight--repos-dir package)))) (condition-case e (and (straight-use-package (intern package)) (not existed-p) (file-directory-p (straight--repos-dir (or local-repo package))) (let* ((commit (and t ...))) (if commit (progn (doom--format-print ...) (if ... nil ...) (straight-vc-check-out-commit recipe commit) t) t)) (setq n (1+ n))) ((debug error) (signal (quote doom-package-error) (list package e (straight--process-get-output)))))))
  (while --dolist-tail-- (setq recipe (car --dolist-tail--)) (straight--with-plist recipe (package local-repo) (let ((existed-p (file-directory-p (straight--repos-dir package)))) (condition-case e (and (straight-use-package (intern package)) (not existed-p) (file-directory-p (straight--repos-dir (or local-repo package))) (let* ((commit ...)) (if commit (progn ... ... ... t) t)) (setq n (1+ n))) ((debug error) (signal (quote doom-package-error) (list package e (straight--process-get-output))))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- (hash-table-values straight--recipe-cache)) recipe) (while --dolist-tail-- (setq recipe (car --dolist-tail--)) (straight--with-plist recipe (package local-repo) (let ((existed-p (file-directory-p (straight--repos-dir package)))) (condition-case e (and (straight-use-package (intern package)) (not existed-p) (file-directory-p (straight--repos-dir ...)) (let* (...) (if commit ... t)) (setq n (1+ n))) ((debug error) (signal (quote doom-package-error) (list package e ...)))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((versions-alist nil) (n 0)) (let ((--dolist-tail-- (hash-table-values straight--recipe-cache)) recipe) (while --dolist-tail-- (setq recipe (car --dolist-tail--)) (straight--with-plist recipe (package local-repo) (let ((existed-p (file-directory-p ...))) (condition-case e (and (straight-use-package ...) (not existed-p) (file-directory-p ...) (let* ... ...) (setq n ...)) ((debug error) (signal ... ...))))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (if (= n 0) (ignore (doom--format-print (doom--format (format (doom--format-class (quote success) "No packages need to be installed"))))) (doom--format-print (doom--format (format (doom--format-class (quote success) "Installed & built %d packages") n))) t))
  (let ((doom-format-indent (+ doom-format-indent-increment doom-format-indent))) (let ((versions-alist nil) (n 0)) (let ((--dolist-tail-- (hash-table-values straight--recipe-cache)) recipe) (while --dolist-tail-- (setq recipe (car --dolist-tail--)) (straight--with-plist recipe (package local-repo) (let ((existed-p ...)) (condition-case e (and ... ... ... ... ...) (... ...)))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (if (= n 0) (ignore (doom--format-print (doom--format (format (doom--format-class ... "No packages need to be installed"))))) (doom--format-print (doom--format (format (doom--format-class (quote success) "Installed & built %d packages") n))) t)))
  doom-cli-packages-install()
  (if noinstall-p (doom--format-print (doom--format (format (doom--format-class (quote warn) "Not installing plugins, as requested")))) (doom--format-print (doom--format (format "Installing plugins"))) (doom-cli-packages-install))
  (let ((default-directory (doom-path "~"))) (if noconfig-p (doom--format-print (doom--format (format (doom--format-class (quote warn) "Not copying private config template, as requested")))) (doom--format-print (doom--format (format (doom--format-class (quote start) "Creating %s") (doom--format-class (quote relpath) doom-private-dir)))) (make-directory doom-private-dir (quote parents)) (let ((doom-format-indent (+ doom-format-indent-increment doom-format-indent))) (doom--format-print (doom--format (format (doom--format-class (quote success) "Created %s") (doom--format-class (quote relpath) doom-private-dir))))) (mapc (function (lambda (file) (let* ((fn file) (filename ...)) (if (let ... ...) (doom--format-print ...) (doom--format-print ...) (let ... ...) (doom--format-print ...))))) (quote (("init.el" lambda nil (insert-file-contents (doom-path doom-emacs-dir "init.example.el"))) ("config.el" lambda nil (insert-file-contents (doom-path doom-core-dir "templates/config.example.el"))) ("packages.el" lambda nil (insert-file-contents (doom-path doom-core-dir "templates/packages.example.el"))))))) (doom-initialize (quote force) (quote noerror)) (doom-initialize-modules) (if noenv-p (doom--format-print (doom--format (format (doom--format-class (quote warn) "Not generating envvars file, as requested")))) (if (file-exists-p doom-env-file) (doom--format-print (doom--format (format (doom--format-class (quote info) "Envvar file already exists, skipping")))) (if (or doom-auto-accept (y-or-n-p "Generate an envvar file? (see `doom help env` for details)")) (progn (doom-cli-reload-env-file (quote force-p)))))) (if noinstall-p (doom--format-print (doom--format (format (doom--format-class (quote warn) "Not installing plugins, as requested")))) (doom--format-print (doom--format (format "Installing plugins"))) (doom-cli-packages-install)) (doom--format-print (doom--format (format "Regenerating autoloads files"))) (doom-cli-reload-autoloads) (if nofonts-p (doom--format-print (doom--format (format (doom--format-class (quote warn) "Not installing fonts, as requested")))) (if (or doom-auto-accept (y-or-n-p "Download and install all-the-icon's fonts?")) (progn (require (quote all-the-icons)) (let ((window-system (cond ... ...))) (all-the-icons-install-fonts (quote yes)))))) (if (file-exists-p "~/.emacs") (progn (doom--format-print (doom--format (format (doom--format-class (quote warn) "A ~/.emacs file was detected. This conflicts with Doom and should be deleted!")))))) (doom--format-print (doom--format (format (doom--format-class (quote success) "\nFinished! Doom is ready to go!\n")))) (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (doom-template-insert "QUICKSTART_INTRO") (doom--format-print (doom--format (format ...)))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))))
  (let ((noconfig-p (cdr (assq (quote noconfig-p) --alist--))) (noenv-p (cdr (assq (quote noenv-p) --alist--))) (noinstall-p (cdr (assq (quote noinstall-p) --alist--))) (nofonts-p (cdr (assq (quote nofonts-p) --alist--))) (_args (cdr (assq (quote _args) --alist--)))) :bare t (doom--format-print (doom--format (format (doom--format-color (quote green) "Installing Doom Emacs!\n")))) (let ((default-directory (doom-path "~"))) (if noconfig-p (doom--format-print (doom--format (format (doom--format-class (quote warn) "Not copying private config template, as requested")))) (doom--format-print (doom--format (format (doom--format-class (quote start) "Creating %s") (doom--format-class (quote relpath) doom-private-dir)))) (make-directory doom-private-dir (quote parents)) (let ((doom-format-indent (+ doom-format-indent-increment doom-format-indent))) (doom--format-print (doom--format (format (doom--format-class ... "Created %s") (doom--format-class ... doom-private-dir))))) (mapc (function (lambda (file) (let* (... ...) (if ... ... ... ... ...)))) (quote (("init.el" lambda nil (insert-file-contents ...)) ("config.el" lambda nil (insert-file-contents ...)) ("packages.el" lambda nil (insert-file-contents ...)))))) (doom-initialize (quote force) (quote noerror)) (doom-initialize-modules) (if noenv-p (doom--format-print (doom--format (format (doom--format-class (quote warn) "Not generating envvars file, as requested")))) (if (file-exists-p doom-env-file) (doom--format-print (doom--format (format (doom--format-class ... "Envvar file already exists, skipping")))) (if (or doom-auto-accept (y-or-n-p "Generate an envvar file? (see `doom help env` for details)")) (progn (doom-cli-reload-env-file (quote force-p)))))) (if noinstall-p (doom--format-print (doom--format (format (doom--format-class (quote warn) "Not installing plugins, as requested")))) (doom--format-print (doom--format (format "Installing plugins"))) (doom-cli-packages-install)) (doom--format-print (doom--format (format "Regenerating autoloads files"))) (doom-cli-reload-autoloads) (if nofonts-p (doom--format-print (doom--format (format (doom--format-class (quote warn) "Not installing fonts, as requested")))) (if (or doom-auto-accept (y-or-n-p "Download and install all-the-icon's fonts?")) (progn (require (quote all-the-icons)) (let ((window-system ...)) (all-the-icons-install-fonts (quote yes)))))) (if (file-exists-p "~/.emacs") (progn (doom--format-print (doom--format (format (doom--format-class ... "A ~/.emacs file was detected. This conflicts with Doom and should be deleted!")))))) (doom--format-print (doom--format (format (doom--format-class (quote success) "\nFinished! Doom is ready to go!\n")))) (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (doom-template-insert "QUICKSTART_INTRO") (doom--format-print (doom--format ...))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))))
  (closure ((plist :bare t) (aliases i) (name . install) t) (--alist--) (ignore --alist--) (let ((noconfig-p (cdr (assq (quote noconfig-p) --alist--))) (noenv-p (cdr (assq (quote noenv-p) --alist--))) (noinstall-p (cdr (assq (quote noinstall-p) --alist--))) (nofonts-p (cdr (assq (quote nofonts-p) --alist--))) (_args (cdr (assq (quote _args) --alist--)))) :bare t (doom--format-print (doom--format (format (doom--format-color (quote green) "Installing Doom Emacs!\n")))) (let ((default-directory (doom-path "~"))) (if noconfig-p (doom--format-print (doom--format (format (doom--format-class ... "Not copying private config template, as requested")))) (doom--format-print (doom--format (format (doom--format-class ... "Creating %s") (doom--format-class ... doom-private-dir)))) (make-directory doom-private-dir (quote parents)) (let ((doom-format-indent (+ doom-format-indent-increment doom-format-indent))) (doom--format-print (doom--format (format ... ...)))) (mapc (function (lambda (file) (let* ... ...))) (quote (("init.el" lambda nil ...) ("config.el" lambda nil ...) ("packages.el" lambda nil ...))))) (doom-initialize (quote force) (quote noerror)) (doom-initialize-modules) (if noenv-p (doom--format-print (doom--format (format (doom--format-class ... "Not generating envvars file, as requested")))) (if (file-exists-p doom-env-file) (doom--format-print (doom--format (format ...))) (if (or doom-auto-accept (y-or-n-p "Generate an envvar file? (see `doom help env` for details)")) (progn (doom-cli-reload-env-file ...))))) (if noinstall-p (doom--format-print (doom--format (format (doom--format-class ... "Not installing plugins, as requested")))) (doom--format-print (doom--format (format "Installing plugins"))) (doom-cli-packages-install)) (doom--format-print (doom--format (format "Regenerating autoloads files"))) (doom-cli-reload-autoloads) (if nofonts-p (doom--format-print (doom--format (format (doom--format-class ... "Not installing fonts, as requested")))) (if (or doom-auto-accept (y-or-n-p "Download and install all-the-icon's fonts?")) (progn (require (quote all-the-icons)) (let (...) (all-the-icons-install-fonts ...))))) (if (file-exists-p "~/.emacs") (progn (doom--format-print (doom--format (format ...))))) (doom--format-print (doom--format (format (doom--format-class (quote success) "\nFinished! Doom is ready to go!\n")))) (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (doom-template-insert "QUICKSTART_INTRO") (doom--format-print ...)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))))))(nil)
  funcall((closure ((plist :bare t) (aliases i) (name . install) t) (--alist--) (ignore --alist--) (let ((noconfig-p (cdr (assq (quote noconfig-p) --alist--))) (noenv-p (cdr (assq (quote noenv-p) --alist--))) (noinstall-p (cdr (assq (quote noinstall-p) --alist--))) (nofonts-p (cdr (assq (quote nofonts-p) --alist--))) (_args (cdr (assq (quote _args) --alist--)))) :bare t (doom--format-print (doom--format (format (doom--format-color (quote green) "Installing Doom Emacs!\n")))) (let ((default-directory (doom-path "~"))) (if noconfig-p (doom--format-print (doom--format (format ...))) (doom--format-print (doom--format (format ... ...))) (make-directory doom-private-dir (quote parents)) (let ((doom-format-indent ...)) (doom--format-print (doom--format ...))) (mapc (function (lambda ... ...)) (quote (... ... ...)))) (doom-initialize (quote force) (quote noerror)) (doom-initialize-modules) (if noenv-p (doom--format-print (doom--format (format ...))) (if (file-exists-p doom-env-file) (doom--format-print (doom--format ...)) (if (or doom-auto-accept ...) (progn ...)))) (if noinstall-p (doom--format-print (doom--format (format ...))) (doom--format-print (doom--format (format "Installing plugins"))) (doom-cli-packages-install)) (doom--format-print (doom--format (format "Regenerating autoloads files"))) (doom-cli-reload-autoloads) (if nofonts-p (doom--format-print (doom--format (format ...))) (if (or doom-auto-accept (y-or-n-p "Download and install all-the-icon's fonts?")) (progn (require ...) (let ... ...)))) (if (file-exists-p "~/.emacs") (progn (doom--format-print (doom--format ...)))) (doom--format-print (doom--format (format (doom--format-class ... "\nFinished! Doom is ready to go!\n")))) (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn ... ...) (and ... ...))))))) nil)
  (if cli (funcall (progn (or (and (memq (type-of cli) cl-struct-doom-cli-tags) t) (signal (quote wrong-type-argument) (list (quote doom-cli) cli))) (aref cli 7)) (doom--cli-process cli args)) (user-error "Couldn't find any %S command" command))
  (let* ((cli (and t (doom-cli-get command)))) (if cli (funcall (progn (or (and (memq (type-of cli) cl-struct-doom-cli-tags) t) (signal (quote wrong-type-argument) (list (quote doom-cli) cli))) (aref cli 7)) (doom--cli-process cli args)) (user-error "Couldn't find any %S command" command)))
  doom-cli-execute("install" nil)
  (and (doom-cli-execute command args) (print! (success "Finished! (%.4fs)") (float-time (time-subtract (current-time) start-time))))
  (let ((start-time (current-time))) (and (doom-cli-execute command args) (print! (success "Finished! (%.4fs)") (float-time (time-subtract (current-time) start-time)))))
  (condition-case e (let ((start-time (current-time))) (and (doom-cli-execute command args) (print! (success "Finished! (%.4fs)") (float-time (time-subtract (current-time) start-time))))) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args)) (error "")) ((debug error) (print! (error "There was an unexpected error:")) (print-group! (print! "%s %s" (bold "Type:") (car e)) (print! (bold "Message:")) (print-group! (print! "%s" (get (car e) (quote error-message)))) (print! (bold "Data:")) (print-group! (if (cdr e) (let ((--dolist-tail-- ...) item) (while --dolist-tail-- (setq item ...) (print! "%S" item) (setq --dolist-tail-- ...))) (print! "n/a"))) (if (string-match-p (regexp-quote straight-process-buffer) (error-message-string e)) (progn (print! (bold "Straight output:")) (print-group! (print! "%s" (straight--process-get-output)))))) (if debug-on-error nil (terpri) (print! (concat "Run the command again with the -d (or --debug) switch to enable debug\n" "mode and (hopefully) generate a backtrace from this error:\n" "\n  %s\n\n" "If you file a bug report, please include it!") (string-join (append (list (file-name-nondirectory load-file-name) "-d" command) args) " ")) (error ""))))
  (cond ((not noninteractive) (print! "Doom launched out of %s (test mode)" (path user-emacs-directory)) (load! "init.el" user-emacs-directory) (doom-run-all-startup-hooks-h)) ((null command) (doom-cli-execute "help")) ((condition-case e (let ((start-time (current-time))) (and (doom-cli-execute command args) (print! (success "Finished! (%.4fs)") (float-time (time-subtract ... start-time))))) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args)) (error "")) ((debug error) (print! (error "There was an unexpected error:")) (print-group! (print! "%s %s" (bold "Type:") (car e)) (print! (bold "Message:")) (print-group! (print! "%s" (get ... ...))) (print! (bold "Data:")) (print-group! (if (cdr e) (let ... ...) (print! "n/a"))) (if (string-match-p (regexp-quote straight-process-buffer) (error-message-string e)) (progn (print! ...) (print-group! ...)))) (if debug-on-error nil (terpri) (print! (concat "Run the command again with the -d (or --debug) switch to enable debug\n" "mode and (hopefully) generate a backtrace from this error:\n" "\n  %s\n\n" "If you file a bug report, please include it!") (string-join (append ... args) " ")) (error ""))))))
  (let ((help-p (cdr (assq (quote help-p) --alist--))) (debug-p (cdr (assq (quote debug-p) --alist--))) (yes-p (cdr (assq (quote yes-p) --alist--))) (emacsdir (cdr (assq (quote emacsdir) --alist--))) (doomdir (cdr (assq (quote doomdir) --alist--))) (localdir (cdr (assq (quote localdir) --alist--))) (command (cdr (assq (quote command) --alist--))) (args (cdr (assq (quote args) --alist--)))) :bare t (if emacsdir (progn (setq user-emacs-directory (file-name-as-directory emacsdir)) (print! (info "EMACSDIR=%s") localdir))) (if doomdir (progn (setenv "DOOMDIR" doomdir) (print! (info "DOOMDIR=%s") localdir))) (if localdir (progn (setenv "DOOMLOCALDIR" localdir) (print! (info "DOOMLOCALDIR=%s") localdir))) (if debug-p (progn (setenv "DEBUG" "1") (setq doom-debug-mode t) (print! (info "Debug mode on")))) (if yes-p (progn (setenv "YES" "1") (setq doom-auto-accept t) (print! (info "Auto-yes on")))) (if help-p (progn (if command (progn (setq args (cons command args)))) (setq command "help"))) (if (equal (user-real-uid) 0) (progn (message (concat "WARNING: This script is running as root. This isn't necessary and is likely\n" "unintentional. It will cause file permissions errors later if you use this\n" "Doom installation on a non-root account.\n")) (if (or doom-auto-accept (y-or-n-p "Continue anyway?")) nil (user-error "Aborted")))) (if (or emacsdir doomdir localdir) (progn (load! "core/core.el" user-emacs-directory))) (cond ((not noninteractive) (print! "Doom launched out of %s (test mode)" (path user-emacs-directory)) (load! "init.el" user-emacs-directory) (doom-run-all-startup-hooks-h)) ((null command) (doom-cli-execute "help")) ((condition-case e (let ((start-time (current-time))) (and (doom-cli-execute command args) (print! (success "Finished! (%.4fs)") (float-time ...)))) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args)) (error "")) ((debug error) (print! (error "There was an unexpected error:")) (print-group! (print! "%s %s" (bold "Type:") (car e)) (print! (bold "Message:")) (print-group! (print! "%s" ...)) (print! (bold "Data:")) (print-group! (if ... ... ...)) (if (string-match-p ... ...) (progn ... ...))) (if debug-on-error nil (terpri) (print! (concat "Run the command again with the -d (or --debug) switch to enable debug\n" "mode and (hopefully) generate a backtrace from this error:\n" "\n  %s\n\n" "If you file a bug report, please include it!") (string-join ... " ")) (error "")))))))
  (lambda (--alist--) (ignore --alist--) (let ((help-p (cdr (assq (quote help-p) --alist--))) (debug-p (cdr (assq (quote debug-p) --alist--))) (yes-p (cdr (assq (quote yes-p) --alist--))) (emacsdir (cdr (assq (quote emacsdir) --alist--))) (doomdir (cdr (assq (quote doomdir) --alist--))) (localdir (cdr (assq (quote localdir) --alist--))) (command (cdr (assq (quote command) --alist--))) (args (cdr (assq (quote args) --alist--)))) :bare t (if emacsdir (progn (setq user-emacs-directory (file-name-as-directory emacsdir)) (print! (info "EMACSDIR=%s") localdir))) (if doomdir (progn (setenv "DOOMDIR" doomdir) (print! (info "DOOMDIR=%s") localdir))) (if localdir (progn (setenv "DOOMLOCALDIR" localdir) (print! (info "DOOMLOCALDIR=%s") localdir))) (if debug-p (progn (setenv "DEBUG" "1") (setq doom-debug-mode t) (print! (info "Debug mode on")))) (if yes-p (progn (setenv "YES" "1") (setq doom-auto-accept t) (print! (info "Auto-yes on")))) (if help-p (progn (if command (progn (setq args (cons command args)))) (setq command "help"))) (if (equal (user-real-uid) 0) (progn (message (concat "WARNING: This script is running as root. This isn't necessary and is likely\n" "unintentional. It will cause file permissions errors later if you use this\n" "Doom installation on a non-root account.\n")) (if (or doom-auto-accept (y-or-n-p "Continue anyway?")) nil (user-error "Aborted")))) (if (or emacsdir doomdir localdir) (progn (load! "core/core.el" user-emacs-directory))) (cond ((not noninteractive) (print! "Doom launched out of %s (test mode)" (path user-emacs-directory)) (load! "init.el" user-emacs-directory) (doom-run-all-startup-hooks-h)) ((null command) (doom-cli-execute "help")) ((condition-case e (let ((start-time ...)) (and (doom-cli-execute command args) (print! ... ...))) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args)) (error "")) ((debug error) (print! (error "There was an unexpected error:")) (print-group! (print! "%s %s" ... ...) (print! ...) (print-group! ...) (print! ...) (print-group! ...) (if ... ...)) (if debug-on-error nil (terpri) (print! ... ...) (error ""))))))))(((command . "install")))
  funcall((lambda (--alist--) (ignore --alist--) (let ((help-p (cdr (assq (quote help-p) --alist--))) (debug-p (cdr (assq (quote debug-p) --alist--))) (yes-p (cdr (assq (quote yes-p) --alist--))) (emacsdir (cdr (assq (quote emacsdir) --alist--))) (doomdir (cdr (assq (quote doomdir) --alist--))) (localdir (cdr (assq (quote localdir) --alist--))) (command (cdr (assq (quote command) --alist--))) (args (cdr (assq (quote args) --alist--)))) :bare t (if emacsdir (progn (setq user-emacs-directory (file-name-as-directory emacsdir)) (print! (info "EMACSDIR=%s") localdir))) (if doomdir (progn (setenv "DOOMDIR" doomdir) (print! (info "DOOMDIR=%s") localdir))) (if localdir (progn (setenv "DOOMLOCALDIR" localdir) (print! (info "DOOMLOCALDIR=%s") localdir))) (if debug-p (progn (setenv "DEBUG" "1") (setq doom-debug-mode t) (print! (info "Debug mode on")))) (if yes-p (progn (setenv "YES" "1") (setq doom-auto-accept t) (print! (info "Auto-yes on")))) (if help-p (progn (if command (progn (setq args ...))) (setq command "help"))) (if (equal (user-real-uid) 0) (progn (message (concat "WARNING: This script is running as root. This isn't necessary and is likely\n" "unintentional. It will cause file permissions errors later if you use this\n" "Doom installation on a non-root account.\n")) (if (or doom-auto-accept (y-or-n-p "Continue anyway?")) nil (user-error "Aborted")))) (if (or emacsdir doomdir localdir) (progn (load! "core/core.el" user-emacs-directory))) (cond ((not noninteractive) (print! "Doom launched out of %s (test mode)" (path user-emacs-directory)) (load! "init.el" user-emacs-directory) (doom-run-all-startup-hooks-h)) ((null command) (doom-cli-execute "help")) ((condition-case e (let (...) (and ... ...)) (user-error (print! ... ...) (print! ... ...) (error "")) ((debug error) (print! ...) (print-group! ... ... ... ... ... ...) (if debug-on-error nil ... ... ...))))))) ((command . "install")))
  (if cli (funcall (progn (or (and (memq (type-of cli) cl-struct-doom-cli-tags) t) (signal (quote wrong-type-argument) (list (quote doom-cli) cli))) (aref cli 7)) (doom--cli-process cli args)) (user-error "Couldn't find any %S command" command))
  (let* ((cli (and t (doom-cli-get command)))) (if cli (funcall (progn (or (and (memq (type-of cli) cl-struct-doom-cli-tags) t) (signal (quote wrong-type-argument) (list (quote doom-cli) cli))) (aref cli 7)) (doom--cli-process cli args)) (user-error "Couldn't find any %S command" command)))
  doom-cli-execute(:main ("install"))
  (let* ((load-prefer-newer t) (loaddir (file-name-directory (file-truename load-file-name))) (emacsdir (getenv "EMACSDIR")) (user-emacs-directory (abbreviate-file-name (or emacsdir (expand-file-name "../" loaddir))))) (setq load-path (cons (expand-file-name "core" user-emacs-directory) load-path)) (require (quote core)) (require (quote core-cli)) (defcli! :main ((help-p ["-h" "--help"] "Same as help command") (debug-p ["-d" "--debug"] "Turns on doom-debug-mode (and debug-on-error)") (yes-p ["-y" "--yes"] "Auto-accept all confirmation prompts") (emacsdir ["--emacsdir" dir] "Use the emacs config at DIR (e.g. ~/.emacs.d)") (doomdir ["--doomdir" dir] "Use the private module at DIR (e.g. ~/.doom.d)") (localdir ["--localdir" dir] "Use DIR as your local storage directory") &optional command &rest args) "A command line interface for managing Doom Emacs.\n\nIncludes package management, diagnostics, unit tests, and byte-compilation.\n\nThis tool also makes it trivial to launch Emacs out of a different folder or\nwith a different private module." :bare t (if emacsdir (progn (setq user-emacs-directory (file-name-as-directory emacsdir)) (print! (info "EMACSDIR=%s") localdir))) (if doomdir (progn (setenv "DOOMDIR" doomdir) (print! (info "DOOMDIR=%s") localdir))) (if localdir (progn (setenv "DOOMLOCALDIR" localdir) (print! (info "DOOMLOCALDIR=%s") localdir))) (if debug-p (progn (setenv "DEBUG" "1") (setq doom-debug-mode t) (print! (info "Debug mode on")))) (if yes-p (progn (setenv "YES" "1") (setq doom-auto-accept t) (print! (info "Auto-yes on")))) (if help-p (progn (if command (progn (setq args (cons command args)))) (setq command "help"))) (if (equal (user-real-uid) 0) (progn (message (concat "WARNING: This script is running as root. This isn't necessary and is likely\n" "unintentional. It will cause file permissions errors later if you use this\n" "Doom installation on a non-root account.\n")) (if (or doom-auto-accept (y-or-n-p "Continue anyway?")) nil (user-error "Aborted")))) (if (or emacsdir doomdir localdir) (progn (load! "core/core.el" user-emacs-directory))) (cond ((not noninteractive) (print! "Doom launched out of %s (test mode)" (path user-emacs-directory)) (load! "init.el" user-emacs-directory) (doom-run-all-startup-hooks-h)) ((null command) (doom-cli-execute "help")) ((condition-case e (let ((start-time ...)) (and (doom-cli-execute command args) (print! ... ...))) (user-error (print! (error "%s\n") (error-message-string e)) (print! (yellow "See 'doom help %s' for documentation on this command.") (car args)) (error "")) ((debug error) (print! (error "There was an unexpected error:")) (print-group! (print! "%s %s" ... ...) (print! ...) (print-group! ...) (print! ...) (print-group! ...) (if ... ...)) (if debug-on-error nil (terpri) (print! ... ...) (error ""))))))) (doom-cli-execute :main (cdr (member "--" argv))) (setq argv nil))
  eval-buffer(#<buffer  *load*> nil "/Users/tamasgal/.emacs.d/bin/doom" nil t)  ; Reading at buffer position 5352
  load-with-code-conversion("/Users/tamasgal/.emacs.d/bin/doom" "/Users/tamasgal/.emacs.d/bin/doom" nil t)
  load("/Users/tamasgal/.emacs.d/bin/doom" nil t t)
  command-line-1(("-scriptload" "/Users/tamasgal/.emacs.d/bin/doom" "--" "install"))
  command-line()
  normal-top-level()
</pre></details>

**Steps to reproduce:**
1. Fresh installation via `git clone ...` and `doom install`

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "NOTIFY ACL GNUTLS LIBXML2 ZLIB MODULES THREADS")
  (build . "Aug 31, 2019")
  (buildopts "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs/26.3/share/info/emacs --prefix=/usr/local/Cellar/emacs/26.3 --with-gnutls --without-x --with-xml2 --without-dbus --with-modules --without-ns --without-imagemagick")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 8a01ef908 2020-01-20 20:17:43 -0500")
  (dir . "~/.rc/doom.d/"))
 (system
  (type . darwin)
  (config . "x86_64-apple-darwin18.6.0")
  (shell . "/usr/local/bin/zsh")
  (uname . "Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64")
  (path "~/.nimble/bin" "/usr/local/Cellar/pyenv-virtualenv/1.1.3/shims" "~/.pyenv/shims" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/opt/X11/bin" "~/.cabal/bin" "/usr/local/MacGPG2/bin" "/usr/local/sbin" "/Applications/DevDesktop/drush" "/usr/local/texlive/2016/bin/x86_64-darwin" "/Library/TeX/texbin" "~/.emacs.d/bin" "/usr/local/Cellar/emacs/26.3/libexec/emacs/26.3/x86_64-apple-darwin18.6.0"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company (ivy +fuzzy) :ui doom doom-dashboard hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs workspaces :editor (evil +everywhere) file-templates multiple-cursors snippets :emacs dired electric ibuffer vc :checkers syntax spell grammar :tools direnv (eval +overlay) (lookup +docsets) lsp magit :lang data emacs-lisp julia latex markdown (org +pandoc +present) (python +lsp) rst sh :app calendar :config (default +bindings +smartparens))
  (packages "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by tamasgal** [comment]
Ahm, sorry I just realised that this is related to some issues at `orgmode.org` as I cannot even access the code base via the web browser: https://code.orgmode.org/bzg/org-mode
I had a similar issue today afternoon which did not report the `fatal: https://code.orgmode.org/bzg/org-mode.git/info/refs not valid: is this a git repository?` error (but something else), so I thought it would be the same.

**Comment by hlissner** [comment]
This repo seems to break often. Perhaps its time we switch to a mirror. Try adding this to `~/.doom.d/packages.el`:

```elisp
(package! org-plus-contrib :recipe (:host github :repo "emacs-straight/org"))
```

**Comment by hlissner** [comment]
You may have to delete `~/.emacs.d/.local/straight/repos/org` first.

**Comment by tamasgal** [comment]
I just realised that the `org-plus-contrib` is not present as a mirror in that Github organisation. Is it called differently there?

```
  → Cloning org (for org-plus-contrib)...
x There was an unexpected error:
  Type: doom-package-error
  Message:
    Error with packages
  Data:
    "org-plus-contrib"
    (error "Failed to run \"git\"; see buffer *straight-process*")
    "Cloning into '/Users/tamasgal/.emacs.d/.local/straight/repos/org'...
    fatal: could not read Username for 'https://github.com': Device not configured
    "
  Straight output:
    Cloning into '/Users/tamasgal/.emacs.d/.local/straight/repos/org'...
    fatal: could not read Username for 'https://github.com': Device not configured
```

**Comment by hlissner** [comment]
As of 964291b we install org from the [emacs-straight/org-mode mirror](https://github.com/emacs-straight/org-mode), which should resolve this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by hlissner** [comment]
@tamasgal We [recently switched](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/packages.el#L26-L30) to https://github.com/emacs-straight/org-mode instead, which is named "org-mode" rather than org-plus-contrib or org. Probably to differentiate it from them (it is equivalent to org-plus-contrib though).

**Comment by gpetrini** [comment]
I had fresh installed emacs 26.3 from source code with module flag and than installed doom emacs (I am not sure if it is related with my problem). Next, I installed org-plu-s-contrib as suggested in this issue. However, when I compile an org file with :ignore: tag, it still do not worked as expected. When I run this same org file in scimax it works fine. There is any other thing I could do?

Here is my personal doom emacs config repo [link](https://github.com/gpetrini/.doom.d)

I am running pop!os 20.04 and zsh if it help.

**Comment by hlissner** [comment]
> I installed org-plu-s-contrib as suggested in this issue

@gpetrini Do not install org yourself, unless you know what you're doing. Enable the `:lang org` module instead (which you have, so you shouldn't need to tussle with installing org to begin with). It will install `org-mode` from a mirror that includes the contrib packages.

**Comment by gpetrini** [comment]
Thank you for the quick response. I enabled `:lang org` as recommended. However, I still have the same problem with `:ignore:` tag. The expected behavior when using this tag is to not export the section title in the output, but I still got it in my PDFs.  I am not sure if it is an org-mode or doom related. I guess that this tag is from `ox-extra.el`.

**Comment by hlissner** [comment]
Wasn't it supposed to be `:noexport:`? I'm not aware of `:ignore:`.

**Comment by gpetrini** [comment]
They similar tags, but have different behaviors. `:noexport` does not export the whole section while `:ignore:` does not export just the section title. I guess that is provided by `ox-extra.el` and that's why I supposed to be related to org-plus-contrib. More precisely, in my previous emacs configuration (based on scimax [link](https://github.com/gpetrini/scimax)) I enabled this feature adding the following code in my config file

```
(require 'package)
(add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/") t)
(add-to-list 'package-selected-packages 'org-plus-contrib)
```
That's why I think is an error in my migration process from scimax to doom. Is there a way to use a similar command as `add-to-list 'package-archives` in doom?


Sorry for the confusing question

**Comment by gpetrini** [comment]
*Update:* Just removing the following lines worked
```
(require 'package)
(add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/") t)
(add-to-list 'package-selected-packages 'org-plus-contrib)
```

Sorry for this huge mess

**Comment by hlissner** [comment]
This should do it:

```lisp
(after! ox
  (require 'ox-extra)
  (ox-extras-activate '(ignore-headlines)))
```

Highly recommend you don't use `package.el`. It's not needed here. `org-extra.el` comes with the org that our module installs.

**Comment by gpetrini** [comment]
Thanks! It worked like a charm!
