### ISSUE TITLE
Could not find package X in recipe repositories

### ISSUE THREAD

**Issue by flyingns** [hlissner/doom-emacs#2802]
After updating doom with `doom upgrade`, or its packages with `doom update`, I get errors like these:

```
Package error: (error Could not find package org-roam in recipe repositories: (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror))
Package error: (error Could not find package company-org-roam in recipe repositories: (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror))
```

And/or errors like these:

```
Cannot open load file: No such file or directory, org-roam
Cannot open load file: No such file or directory, org-superstar
```

**Comment by jadestrong** [comment]
Me too.

**Comment by hlissner** [comment]
It's a known issue where your local melpa repo isn't being updated. I'm working on a fix, but in the mean time you'll need to do:

```sh
# Update MELPA
cd ~/.emacs.d/.local/straight/repos/melpa
git pull

# Clear straight's cache
rm -f ~/.emacs.d/.local/straight/build-cache.el
doom sync
```

**Comment by jcf** [comment]
I've encountered this same issue, and the recommended workaround fails like so:

``` sh
$ doom sync
Building straight...
Building straight...done
Building use-package...
Building use-package → Building bind-key...
Building use-package → Building bind-key...done
Building use-package...
Building use-package...done
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "~/.emacs.d/.local/env"
  - Scraping shell environment
    - Ignoring HOME=/Users/jcf
    - Ignoring GPG_TTY=/dev/ttys006
    - Ignoring PWD=/Users/jcf/.emacs.d/.local/straight/repos/melpa
    - Ignoring __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x2
    - Ignoring SSH_AUTH_SOCK=/Users/jcf/.gnupg/S.gpg-agent.ssh
    - Ignoring TERM=xterm-256color
    ✓ Successfully generated "~/.emacs.d/.local/env"
  > (Re)generating core autoloads...
    > Generating core autoloads...
    > Byte-compiling core autoloads file...
    ✓ Generated .local/autoloads.elc
  > Installing packages...
    → Cloning auto-minor-mode...
x There was an unexpected error:
  Type: doom-package-error
  Message:
    Error with packages
  Data:
    "auto-minor-mode"
    (error "Failed to run \"git\"; see buffer *straight-process*")
    "fatal: destination path '/Users/jcf/.emacs.d/.local/straight/repos/auto-minor-mode' already exists and is not an empty directory.
    "
  Straight output:
    fatal: destination path '/Users/jcf/.emacs.d/.local/straight/repos/auto-minor-mode' already exists and is not an empty directory.


Run the command again with the -d (or --debug) switch to enable debug
mode and (hopefully) generate a backtrace from this error:

  doom -d sync

If you file a bug report, please include it!
```

**Comment by hlissner** [comment]
For posterity and to avoid confusion, @jcf's issue is unrelated to this one (see #2937, which was resolved separately).

**Comment by glencjones** [comment]
I had the same issue for shellcheck discovered it was also in my config, removed it and message has now gone...

**Comment by hlissner** [comment]
As of 0e851ac this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by kawaiier** [comment]
Had the same problem. Just tried **doom upgrade/update** and got this
```
Type: error
  Message:
    error
  Data:
    "Could not find package org-superstar in recipe repositories: (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror)"
```

**Comment by nikolauska** [comment]
@kawaiier Had the same issue `org-superstar`. Updating melpa manually as mentioned above fixed the issue

**Comment by harrisj** [comment]
I have done the fix as mentioned above, but it breaks again the next time I run `doom upgrade`

**Comment by DhruvDh** [comment]
I am having the same problem with `org-reveal`, following the above steps doesn't seem to fix it, melpa was already up to date, as were all of the other mirrors, but `doom sync` gives the error -

```
x There was an unexpected error:
  Type: error
  Message:
    error
  Data:
    "Could not find package org-reveal in recipe repositories: (org-elpa melpa gnu-elpa-mirror emacsmirror-mirror)"
```

**Comment by VitalyAnkh** [comment]
@harrisj I have the same issue :sweat_smile:

**Comment by hlissner** [comment]
@harrisj @VitalyAnkh Try

```sh
git -C ~/.emacs.d pull
git -C ~/.emacs.d/.local/straight/repos/melpa pull
rm -rf ~/.emacs.d/.local/straight/repos/org-superstar
rm -f ~/.emacs.d/.local/straight/build-cache.el
doom sync
```

**Comment by samwhitlock** [comment]
In case anyone happens upon this for org superstar in particular, @hlissner changed superstar to require `(org +pretty)` in `init.el` a few days ago (due to speed issues).

If the above package refreshing stuff doesn't work, you may need to add this flag.
