### ISSUE TITLE
Inserting [ ] and [/] in org without deleting paired symbols?

### ISSUE THREAD

**Issue by AloisJanicek** [hlissner/doom-emacs#285]
Hi,  
when I try to type `[/]` at the end of heading, I got two forward slashes and I must delete one. Same goes for checkbox `[ ]`, where after having cursor between opening and closing square bracket, I press "SPC" in Insert mode and I got two spaces and I must remove one otherwise checkbox is not valid.  
Is this intended behaviour or could I did something in my private module to cause it?

**Comment by hlissner** [comment]
`smartparens` has been misconfigured for org-mode. I have a fix for this sitting my local branch that I've tested for a while. I'll let you know once it hits `develop`.

**Comment by AloisJanicek** [comment]
Thank you, I am looking forward to it.

**Comment by hlissner** [comment]
I just pushed a fix for this to `develop`. Please give it a try.

In any case, I'll keep this issue open until it gets merged into `master`.

**Comment by AloisJanicek** [comment]
I can now type org's cookie `[/]` seamlessly, thanks!  
Unfortunately issue with getting two spaces (instead of one) when I want to construct first checkbox list item and I have cursor between `[` and `]` is still present.

**Comment by hlissner** [comment]
I've added a line to my private module to fix this. In case you've created your own, you'll need this:

```emacs-lisp
(map! :map org-mode-map [remap doom/inflate-space-maybe] #'self-insert-command)
```

**Comment by AloisJanicek** [comment]
I can confirm, it is now fixed, thank you.  
Hover I have several serious problems with current develop branch (no modeline, error on startup in `solaire-mode.elc`, some commands are not loading line `winner-undo`).  
I am facing here (probably stupid) dilemma, because as I beginner I have a hard time to recognize if I am doing something wrong on my side and I will waste your time with opening issues. I have noticed that mindsets vary among maintainers regard to this and I don't want to upset you.

**Comment by hlissner** [comment]
I appreciate the consideration, but don't worry, I really don't mind.

Anyhow, the last few days have been especially hectic for the `develop` branch; I've introduced a laundry list of breaking changes that could be causing your problems. So try running this:

```bash
make clean
make
make update
make compile-elpa
```

This should nuke any inconsistent state lingering from previous versions. If that doesn't resolve your issue, let me know, and please include:

1. Any error messages you get (see `M-x view-echo-area-messages`)
2. The output of `DEBUG=1 make doctor`

**Comment by hlissner** [comment]
After some experimenting, it turns out that the errors you were seeing were, in fact, caused by solaire-mode. I've pushed a fix for it. Please give it a try and let me know!

**Comment by AloisJanicek** [comment]
Yes, everything is fixed, including modeline and `winner-undo'.  
There is nothing interesting in echo-area-messages anymore:   
```
.emacs.d/core/autoload/buffers.el: ‘when-let’ is an obsolete macro (as of 26.1); use ‘when-let*’ instead.  
.emacs.d/core/autoload/popups.el: ‘when-let’ is an obsolete macro (as of 26.1); use ‘when-let*’ instead.  
.emacs.d/core/autoload/popups.el: ‘if-let’ is an obsolete macro (as of 26.1); use ‘if-let*’ instead.  
.emacs.d/core/autoload/popups.el: ‘when-let’ is an obsolete macro (as of 26.1); use ‘when-let*’ instead.  
.emacs.d/core/autoload/popups.el: ‘if-let’ is an obsolete macro (as of 26.1); use ‘if-let*’ instead.  
.emacs.d/core/autoload/popups.el: ‘when-let’ is an obsolete macro (as of 26.1); use ‘when-let*’ instead. [2 times]  
.emacs.d/core/autoload/popups.el: ‘if-let’ is an obsolete macro (as of 26.1); use ‘if-let*’ instead. [2 times]  
.emacs.d/core/autoload/popups.el: ‘when-let’ is an obsolete macro (as of 26.1); use ‘when-let*’ instead.  
Loading /home/ajanicek/.emacs.d/.local/@aj-tpe/etc/recentf...done  
Cleaning up the recentf list...done (0 removed)  
Doom loaded 263 packages across 65 modules in 1.151s
```

but make doctor gives some kind of error (it could not find something?):  

```
~/.emacs.d (develop) $ DEBUG=1 make doctor
DOOM Doctor
Running Emacs v26.0.90, commit 0ff5966379c192ca74607575efb84700d72d163c

Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS NOTIFY ACL GNUTLS
  LIBXML2 FREETYPE LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES
  XWIDGETS LIBSYSTEMD LCMS2
uname -a:
  Linux aj-tpe 4.14.4-1-ARCH #1 SMP PREEMPT Tue Dec 5 19:10:06 UTC 2017
  x86_64 GNU/Linux

Attempt to load DOOM: success! Loaded v2.0.7
Revision 0ff5966379c192ca74607575efb84700d72d163c

----

test-emacs
test-windows
test-fonts
Found font material-design-icons.ttf
Found font weathericons.ttf
Found font octicons.ttf
Found font fontawesome.ttf
Found font file-icons.ttf
Found font all-the-icons.ttf
test-gnutls
test-tls
Verified elpa.gnu.org
Verified melpa.org
peculiar error
make: *** [Makefile:80: doctor] Error 255

**Comment by hlissner** [comment]
The fix for the original checkbox issue is in `master` so I'll close this issue.

Regarding your "peculiar error" when running make doctor, I've been following this issue for a long time (see #175). I suspect it has to do with package.el failing its TLS validations, which I will indirectly fix when I dump package.el in favor of a straight.el for 2.1.
