### ISSUE TITLE
Issues with light modeline

### ISSUE THREAD

**Issue by athv** [hlissner/doom-emacs#2971]
**What did you expect to happen?**
I've tried to open up a buffer that adds a string to the modeline (`pyenv-mode`, for example).

**What actually happened?**
The buffer opens up normally, but there are several issues.

1. When you open up a buffer, you get this error (even if debugger is turned off, you can still see a little message in minibuffer):

<pre><details>
Debugger entered--Lisp error: (void-function doom-modeline-update-env)
  (doom-modeline-update-env)
  (progn (select-window (car save-selected-window--state) (quote norecord)) (doom-modeline-update-env) (force-mode-line-update))
  (unwind-protect (progn (select-window (car save-selected-window--state) (quote norecord)) (doom-modeline-update-env) (force-mode-line-update)) (internal--after-with-selected-window save-selected-window--state))
  (save-current-buffer (unwind-protect (progn (select-window (car save-selected-window--state) (quote norecord)) (doom-modeline-update-env) (force-mode-line-update)) (internal--after-with-selected-window save-selected-window--state)))
  (let ((save-selected-window--state (internal--before-with-selected-window window))) (save-current-buffer (unwind-protect (progn (select-window (car save-selected-window--state) (quote norecord)) (doom-modeline-update-env) (force-mode-line-update)) (internal--after-with-selected-window save-selected-window--state))))
  (let ((window (car --dolist-tail--))) (let ((save-selected-window--state (internal--before-with-selected-window window))) (save-current-buffer (unwind-protect (progn (select-window (car save-selected-window--state) (quote norecord)) (doom-modeline-update-env) (force-mode-line-update)) (internal--after-with-selected-window save-selected-window--state)))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((window (car --dolist-tail--))) (let ((save-selected-window--state (internal--before-with-selected-window window))) (save-current-buffer (unwind-protect (progn (select-window (car save-selected-window--state) (quote norecord)) (doom-modeline-update-env) (force-mode-line-update)) (internal--after-with-selected-window save-selected-window--state)))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((--dolist-tail-- (window-list))) (while --dolist-tail-- (let ((window (car --dolist-tail--))) (let ((save-selected-window--state (internal--before-with-selected-window window))) (save-current-buffer (unwind-protect (progn (select-window ... ...) (doom-modeline-update-env) (force-mode-line-update)) (internal--after-with-selected-window save-selected-window--state)))) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  +modeline-update-env-in-all-windows-h("/home/toki/.pyenv/versions/3.6.9/envs/redoez")
  apply(+modeline-update-env-in-all-windows-h "/home/toki/.pyenv/versions/3.6.9/envs/redoez")
  pythonic-activate("/home/toki/.pyenv/versions/3.6.9/envs/redoez")
  pyenv-mode-set("3.6.9/envs/redoez")
  (if +pyenv--version (pyenv-mode-set +pyenv--version) (pyenv-mode-unset))
  (progn (if (not (local-variable-p (quote +pyenv--version))) (progn (make-local-variable (quote +pyenv--version)) (setq +pyenv--version (+python-pyenv-read-version-from-file)))) (if +pyenv--version (pyenv-mode-set +pyenv--version) (pyenv-mode-unset)))
  (if (eq major-mode (quote python-mode)) (progn (if (not (local-variable-p (quote +pyenv--version))) (progn (make-local-variable (quote +pyenv--version)) (setq +pyenv--version (+python-pyenv-read-version-from-file)))) (if +pyenv--version (pyenv-mode-set +pyenv--version) (pyenv-mode-unset))))
  +python-pyenv-mode-set-auto-h()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook python-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook python-mode-hook))
  run-mode-hooks(python-mode-hook)
  python-mode()
  set-auto-mode-0(python-mode nil)
  #f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x1b5abb>)()
  apply(#f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x1b5abb>) nil)
  so-long--set-auto-mode(#f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x1b5abb>))
  apply(so-long--set-auto-mode #f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x1b5abb>) nil)
  #f(advice-wrapper :around #f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x1b5abb>) so-long--set-auto-mode)()
  apply(#f(advice-wrapper :around #f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x1b5abb>) so-long--set-auto-mode) nil)
  set-auto-mode()
  normal-mode(t)
  #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1b52df>)(nil t)
  apply(#f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1b52df>) (nil t))
  (if (setq doom-large-file-p (and buffer-file-name (not doom-large-file-p) (file-exists-p buffer-file-name) (condition-case nil (progn (> (nth 7 (file-attributes buffer-file-name)) (* 1024 1024 (assoc-default buffer-file-name doom-large-file-size-alist ...)))) (error nil)))) (prog1 (apply orig-fn args) (if (memq major-mode doom-large-file-excluded-modes) (setq doom-large-file-p nil) (if (fboundp (quote so-long-minor-mode)) (progn (so-long-minor-mode 1))) (message "Large file detected! Cutting a few corners to improve performance..."))) (apply orig-fn args))
  doom--optimize-for-large-files-a(#f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1b52df>) nil t)
  apply(doom--optimize-for-large-files-a #f(compiled-function (&optional error warn noauto after-find-file-from-revert-buffer nomodes) "Called after finding a file and by the default revert function.\nSets buffer mode, parses file-local and directory-local variables.\nOptional args ERROR, WARN, and NOAUTO: ERROR non-nil means there was an\nerror in reading the file.  WARN non-nil means warn if there\nexists an auto-save file more recent than the visited file.\nNOAUTO means don't mess with auto-save mode.\nFourth arg AFTER-FIND-FILE-FROM-REVERT-BUFFER is ignored\n(see `revert-buffer-in-progress-p' for similar functionality).\nFifth arg NOMODES non-nil means don't alter the file's modes.\nFinishes by calling the functions in `find-file-hook'\nunless NOMODES is non-nil." #<bytecode 0x1b52df>) (nil t))
  after-find-file(nil t)
  find-file-noselect-1(#<buffer fetch.py> "~/Projects/redoez/core/management/commands/fetch.py" nil nil "~/Projects/redoez/core/management/commands/fetch.py" (274680 64769))
  find-file-noselect("/home/toki/Projects/redoez/core/management/commands/fetch.py" nil nil nil)
  find-file("/home/toki/Projects/redoez/core/management/commands/fetch.py")
  #f(compiled-function (file) "Find FILE and run `projectile-find-file-hook'." #<bytecode 0x15b1b99>)("core/management/commands/fetch.py")
  apply(#f(compiled-function (file) "Find FILE and run `projectile-find-file-hook'." #<bytecode 0x15b1b99>) "core/management/commands/fetch.py")
  (let ((default-directory (ivy-state-directory ivy-last))) (apply orig-fn args))
  +ivy--run-from-ivy-directory-a(#f(compiled-function (file) "Find FILE and run `projectile-find-file-hook'." #<bytecode 0x15b1b99>) "core/management/commands/fetch.py")
  apply(+ivy--run-from-ivy-directory-a #f(compiled-function (file) "Find FILE and run `projectile-find-file-hook'." #<bytecode 0x15b1b99>) "core/management/commands/fetch.py")
  counsel-projectile-find-file-action("core/management/commands/fetch.py")
  ivy-call()
  ivy-read("[redoez] Find file: " ("../../.emacs.d/modules/ui/modeline/autoload.el" "../../.emacs.d/modules/ui/modeline/+light.el" ".env" ".flake8" ".gitignore" "core/__init__.py" "core/admin.py" "core/apps.py" "core/management/commands/__init__.py" "core/management/commands/fetch.py" "core/migrations/0001_initial.py" "core/migrations/0002_auto_20200424_1630.py" "core/migrations/0003_item.py" "core/migrations/0004_auto_20200425_1243.py" "core/migrations/__init__.py" "core/models.py" "core/serializers.py" "core/tests.py" "core/urls.py" "core/views.py" "manage.py" "pyproject.toml" "redoez/__init__.py" "redoez/settings/__init__.py" "redoez/settings/base.py" "redoez/settings/development.py" "redoez/settings/production.py" "redoez/urls.py" "redoez/wsgi.py") :matcher counsel--find-file-matcher :require-match t :sort nil :action (1 ("o" counsel-projectile-find-file-action "current window") ("j" counsel-projectile-find-file-action-other-window "other window") ("x" counsel-projectile-find-file-action-extern "open externally") ("r" counsel-projectile-find-file-action-root "open as root") ("m" counsel-projectile-find-file-action-find-file-manually "find file manually") ("k" counsel-projectile-find-file-action-delete "delete") ("p" counsel-projectile-find-file-action-switch-project "switch project")) :caller counsel-projectile-find-file)
  counsel-projectile-find-file(nil)
  funcall-interactively(counsel-projectile-find-file nil)
  call-interactively(counsel-projectile-find-file)
  (cond ((and project-root (file-equal-p project-root projectile-project-root)) (if (doom-project-p projectile-project-root) nil (setq projectile-enable-caching nil)) (call-interactively (if (doom-module-p :completion (quote ivy)) (function counsel-projectile-find-file) (function projectile-find-file)))) ((fboundp (quote counsel-file-jump)) (call-interactively (function counsel-file-jump))) ((project-current) (project-find-file-in nil (list default-directory) nil)) ((fboundp (quote helm-find-files)) (call-interactively (function helm-find-files))) ((call-interactively (function find-file))))
  (let* ((default-directory (file-truename (expand-file-name dir))) (project-root (doom-project-root default-directory)) (projectile-project-root default-directory) (projectile-enable-caching projectile-enable-caching)) (cond ((and project-root (file-equal-p project-root projectile-project-root)) (if (doom-project-p projectile-project-root) nil (setq projectile-enable-caching nil)) (call-interactively (if (doom-module-p :completion (quote ivy)) (function counsel-projectile-find-file) (function projectile-find-file)))) ((fboundp (quote counsel-file-jump)) (call-interactively (function counsel-file-jump))) ((project-current) (project-find-file-in nil (list default-directory) nil)) ((fboundp (quote helm-find-files)) (call-interactively (function helm-find-files))) ((call-interactively (function find-file)))))
  doom-project-find-file("~/Projects/redoez/")
  funcall(doom-project-find-file "~/Projects/redoez/")
  (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir))
  (let* ((persp (let ((project-name (doom-project-name +workspaces--project-dir))) (or (+workspace-get project-name t) (+workspace-new project-name)))) (new-name (progn (or (and (memq (type-of persp) cl-struct-perspective-tags) t) (signal (quote wrong-type-argument) (list (quote perspective) persp))) (aref persp 1)))) (+workspace-switch new-name) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir)) (+workspace-message (format "Switched to '%s' in new workspace" new-name) (quote success)))
  (if (and (not (null +workspaces-on-switch-project-behavior)) (or (eq +workspaces-on-switch-project-behavior t) (equal (safe-persp-name (get-current-persp)) persp-nil-name) (+workspace-buffer-list))) (let* ((persp (let ((project-name (doom-project-name +workspaces--project-dir))) (or (+workspace-get project-name t) (+workspace-new project-name)))) (new-name (progn (or (and (memq ... cl-struct-perspective-tags) t) (signal (quote wrong-type-argument) (list ... persp))) (aref persp 1)))) (+workspace-switch new-name) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir)) (+workspace-message (format "Switched to '%s' in new workspace" new-name) (quote success))) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer) (message "Switched to '%s'" (doom-project-name +workspaces--project-dir))) (condition-case err (+workspace-rename (+workspace-current-name) (doom-project-name +workspaces--project-dir)) ((debug error) (message "Workspace error: %s" err) nil)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir)))
  (unwind-protect (if (and (not (null +workspaces-on-switch-project-behavior)) (or (eq +workspaces-on-switch-project-behavior t) (equal (safe-persp-name (get-current-persp)) persp-nil-name) (+workspace-buffer-list))) (let* ((persp (let ((project-name ...)) (or (+workspace-get project-name t) (+workspace-new project-name)))) (new-name (progn (or (and ... t) (signal ... ...)) (aref persp 1)))) (+workspace-switch new-name) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir)) (+workspace-message (format "Switched to '%s' in new workspace" new-name) (quote success))) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer) (message "Switched to '%s'" (doom-project-name +workspaces--project-dir))) (condition-case err (+workspace-rename (+workspace-current-name) (doom-project-name +workspaces--project-dir)) ((debug error) (message "Workspace error: %s" err) nil)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir))) (run-hooks (quote projectile-after-switch-project-hook)) (setq +workspaces--project-dir nil))
  (progn (if projectile-before-switch-project-hook (progn (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer) (run-hooks ...)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))))) (unwind-protect (if (and (not (null +workspaces-on-switch-project-behavior)) (or (eq +workspaces-on-switch-project-behavior t) (equal (safe-persp-name (get-current-persp)) persp-nil-name) (+workspace-buffer-list))) (let* ((persp (let (...) (or ... ...))) (new-name (progn (or ... ...) (aref persp 1)))) (+workspace-switch new-name) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir)) (+workspace-message (format "Switched to '%s' in new workspace" new-name) (quote success))) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer) (message "Switched to '%s'" (doom-project-name +workspaces--project-dir))) (condition-case err (+workspace-rename (+workspace-current-name) (doom-project-name +workspaces--project-dir)) ((debug error) (message "Workspace error: %s" err) nil)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir))) (run-hooks (quote projectile-after-switch-project-hook)) (setq +workspaces--project-dir nil)))
  (if (and persp-mode +workspaces--project-dir) (progn (if projectile-before-switch-project-hook (progn (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn ... ... ...) (and ... ...)))))) (unwind-protect (if (and (not (null +workspaces-on-switch-project-behavior)) (or (eq +workspaces-on-switch-project-behavior t) (equal (safe-persp-name ...) persp-nil-name) (+workspace-buffer-list))) (let* ((persp (let ... ...)) (new-name (progn ... ...))) (+workspace-switch new-name) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir)) (+workspace-message (format "Switched to '%s' in new workspace" new-name) (quote success))) (save-current-buffer (set-buffer (doom-fallback-buffer)) (setq default-directory +workspaces--project-dir) (hack-dir-local-variables-non-file-buffer) (message "Switched to '%s'" (doom-project-name +workspaces--project-dir))) (condition-case err (+workspace-rename (+workspace-current-name) (doom-project-name +workspaces--project-dir)) ((debug error) (message "Workspace error: %s" err) nil)) (if current-prefix-arg nil (funcall +workspaces-switch-project-function +workspaces--project-dir))) (run-hooks (quote projectile-after-switch-project-hook)) (setq +workspaces--project-dir nil))))
  +workspaces-switch-to-project-h("~/Projects/redoez/")
  ivy-call()
  ivy-read("[.doom.d] Switch to project: " ("~/.doom.d/" "~/Projects/redoez/" "~/.emacs.d/" "~/Projects/euler/") :preselect "~/.doom.d/" :action (1 ("o" +workspaces-switch-to-project-h "open project in new workspace") ("O" counsel-projectile-switch-project-action "jump to a project buffer or file") ("f" counsel-projectile-switch-project-action-find-file "jump to a project file") ("d" counsel-projectile-switch-project-action-find-dir "jump to a project directory") ("b" counsel-projectile-switch-project-action-switch-to-buffer "jump to a project buffer") ("m" counsel-projectile-switch-project-action-find-file-manually "find file manually from project root") ("w" counsel-projectile-switch-project-action-save-all-buffers "save all project buffers") ("k" counsel-projectile-switch-project-action-kill-buffers "kill all project buffers") ("r" counsel-projectile-switch-project-action-remove-known-project "remove project from known projects") ("c" counsel-projectile-switch-project-action-compile "run project compilation command") ("C" counsel-projectile-switch-project-action-configure "run project configure command") ("e" counsel-projectile-switch-project-action-edit-dir-locals "edit project dir-locals") ("v" counsel-projectile-switch-project-action-vc "open project in vc-dir / magit / monky") ("s" (lambda (project) (let ((projectile-switch-project-action (lambda nil ...))) (counsel-projectile-switch-project-by-name project))) "search project") ("xs" counsel-projectile-switch-project-action-run-shell "invoke shell from project root") ("xe" counsel-projectile-switch-project-action-run-eshell "invoke eshell from project root") ("xt" counsel-projectile-switch-project-action-run-term "invoke term from project root") ("X" counsel-projectile-switch-project-action-org-capture "org-capture into project")) :require-match t :sort nil :caller counsel-projectile-switch-project)
  counsel-projectile-switch-project()
  funcall-interactively(counsel-projectile-switch-project)
  call-interactively(counsel-projectile-switch-project nil nil)
  command-execute(counsel-projectile-switch-project)
</pre></details>

I've managed to fix it by adding this code to `+light.el` but it's probably a very stupid solution.

```elisp
(defun doom-modeline-update-env () nil)
```
2. If you open up neotree, you **sometimes** get this error, and the buffer won't open up at all:

<pre><details>
Debugger entered--Lisp error: (void-function set-modeline!)
  (set-modeline! name)
  +modeline-set-special-format-h()
  run-hooks(change-major-mode-after-body-hook special-mode-hook neotree-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook special-mode-hook neotree-mode-hook))
  run-mode-hooks(neotree-mode-hook)
  neotree-mode()
  neo-buffer--create()
  neo-global--get-buffer(t)
  neo-global--create-window()
  neo-global--get-window(t)
  neo-global--open-dir("/home/toki/Projects/redoez/")
  neotree-dir("/home/toki/Projects/redoez/")
  (if (neo-global--window-exists-p) (neotree-hide) (neotree-dir (or (doom-project-root) default-directory)))
  +neotree/open()
  funcall-interactively(+neotree/open)
  call-interactively(+neotree/open nil nil)
  command-execute(+neotree/open)
</details></pre>

3. If you try to exit by typing `:q`, you **might** get similar error (can't even copy the backtrace for some reason), and the program won't exit.

I've also encountered some problems with company while using this module flag but I can't reproduce them, might be unrelated.

**Steps to reproduce:**
1. Add `+light` to `:ui modeline`.
2. Reload and restart Emacs.
3. Open up a project that uses `pyenv` (for example).
4. Open up neotree (for the second issue)

**System information:**
<pre><details>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2")
  (build . "мар 26, 2020")
  (buildopts "--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-mEZBk7/emacs-26.3+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro'")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 30dea4bf0 2020-04-25 02:55:06 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 x86_64")
  (path "~/.pyenv/plugins/pyenv-virtualenv/shims" "~/.pyenv/shims" "~/.pyenv/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/snap/bin" "/usr/lib/emacs/26.3/x86_64-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo (modeline +light) nav-flash neotree ophints (popup +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors snippets :emacs dired electric undo vc :term term :checkers syntax grammar :tools debugger (eval +overlay) lookup magit pass :lang data emacs-lisp javascript markdown org (python +pyenv) rest sh web :app irc :config (default +bindings +smartparens))
  (packages (reverse-im :pin "a2a75a929f"))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details> 

**Additional details:**
- Include a link to your private config
- Include screenshots/casts of your issue
- If you mention key sequences, include what commands they're bound to (use `SPC
  h k KEY` or `C-h h k KEY` to inspect keys).
- Include any warnings or errors logged to \*Messages\* (use `M-x
  view-echo-area-messages` to see it).

**Comment by hlissner** [comment]
As of aff4a33 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by athv** [comment]
I'm not sure if I should open up a new issue, but since I've already mentioned it here, I'll reopen it.

aff4a337ace9b1b73e65c9ceba846ca76e646128 indeed fixed the issue with `doom-modeline-update-env`. However, I still get `(void-function set-modeline!)`. This behavior is really unpredictable and can't say exactly how to reproduce it. I just use Emacs normally for a while, and at some moment, when I try to open a neotree or magit I get this error.

Here's another backtrace:
<pre><details>
Debugger entered--Lisp error: (void-function set-modeline!)
  (set-modeline! name)
  +modeline-set-special-format-h()
  run-hooks(change-major-mode-after-body-hook special-mode-hook magit-section-mode-hook magit-mode-hook magit-status-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook special-mode-hook magit-section-mode-hook magit-mode-hook magit-status-mode-hook))
  run-mode-hooks(magit-status-mode-hook)
  magit-status-mode()
  magit-setup-buffer-internal(magit-status-mode nil ((magit-buffer-diff-args ("--no-ext-diff")) (magit-buffer-diff-files nil) (magit-buffer-log-args ("-n256" "--decorate")) (magit-buffer-log-files nil)))
  magit-status-setup-buffer("/home/toki/.emacs.d/")
  magit-status(nil ((4 . 2) (("/home/toki/.emacs.d/" . magit-toplevel) . "/home/toki/.emacs.d/") (("/home/toki/.emacs.d/" "rev-parse" "--show-toplevel") . "/home/toki/.emacs.d")))
  funcall-interactively(magit-status nil ((4 . 2) (("/home/toki/.emacs.d/" . magit-toplevel) . "/home/toki/.emacs.d/") (("/home/toki/.emacs.d/" "rev-parse" "--show-toplevel") . "/home/toki/.emacs.d")))
  call-interactively(magit-status nil nil)
  command-execute(magit-status)
</pre></details>

**Comment by hlissner** [comment]
55d3417 should resolve the `set-modeline!` issue. Let me know if that isn't the case and I'll reopen the issue.
