### ISSUE TITLE
Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument stringp nil)

### ISSUE THREAD

**Issue by flyingns** [hlissner/doom-emacs#3072]
Update to latest commit.

**What did you expect to happen?**

Press `SPC RET` to jump to bookmark

**What actually happened?**

Press `SPC RET` prompt:
`Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument stringp nil)`
However, directly running with `M-x bookmark-jump` not have this prompt.

**System information:**
<details><pre>
Mac OS mojave
emacs-plus 26.3
</pre></details>

**Comment by hlissner** [comment]
I think this may have been fixed by #3071. Please update and let me know.

**Comment by flyingns** [comment]
Updated, but not resolved.

**Comment by hlissner** [comment]
Are you sure you updated Doom with `doom upgrade`, and not `doom update`? After updating ivy, I can no longer reproduce the issue.

**Comment by flyingns** [comment]
This is a very strange thing, I solved this problem in `MacOS mojave`, but the same operation is not solved in `manjaro linux`.

**Comment by flyingns** [comment]
This error reappeared on MacOS mojave.

**Comment by rhysday** [comment]
Anyone else having this problem again? happened to me after I added a few packages and did doom upgrade. Also edited my config.el but not sure if that caused it

**Comment by Bounga** [comment]
I do have the same error.

```
Doom v2.0.9 (46d6d0b586b868c21a534bacd6650a4ff0f753c3)
Emacs v28.0.50
Branch: develop
Build date: 2020-06-29 15:12:30 -0400
```

**Comment by gitbugr** [comment]
I had this after upgrading through doom itself. Running again via the command line fixed it for me;
```~/.emacs.d/bin/doom upgrade```

I'm on MacOS Catalina

**Comment by hlissner** [comment]
I suspect this was an upstream issue. I've since bumped ivy (swiper) a couple times. Since I can't reproduce it I'll consider this resolved. Let me know if that isn't the case (and please include your `M-x doom/info` when you do).

**Comment by Bounga** [comment]
I just `~/.emacs.d/bin/doom upgrade` then restarted Emacs and tried again and I still have the exact same issue.

Here is my `doom/info`:

<details>

```
emacs   version    28.0.50
        features   JPEG TIFF GIF PNG RSVG IMAGEMAGICK DBUS GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS XWIDGETS PDUMPER LCMS2 GMP
        build      Apr 24, 2020
        buildopts  (--enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-head/HEAD-bef617d_1/share/info/emacs --prefix=/usr/local/Cellar/emacs-head/HEAD-bef617d_1 --without-x --with-dbus --with-imagemagick --with-modules --without-pop --with-gnutls --with-rsvg --with-xml2 --with-xwidgets --with-harfbuzz --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop aac73f4c0 2020-07-24 02:22:25 -0400
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.3.0
        shell      /usr/local/bin/fish
        uname      Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
        path       (~/.rbenv/shims ~/bin/elixir-ls/ /usr/local/MacGPG2/bin /Library/TeX/texbin /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/sbin /sbin /usr/local/Cellar/emacs-head/HEAD-bef617d_1/libexec/emacs/28.0.50/x86_64-apple-darwin19.3.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company (ivy +icons) :ui doom doom-dashboard hl-todo modeline ophints (popup +defaults) treemacs vc-gutter window-select workspaces zen :editor file-templates (format +onsave) (objed +manual) snippets word-wrap :emacs (dired +icons) electric (ibuffer +icons) undo vc :term eshell vterm :checkers syntax (spell +everywhere) grammar :tools debugger docker (eval +overlay) gist (lookup +docsets +dictionary) (lsp +peek) macos (magit +forge) pass pdf :lang (cc +lsp) (elixir +lsp) emacs-lisp json (javascript +lsp) markdown (org +pandoc +present) plantuml (ruby +rbenv +rails +lsp) sh (web +lsp) (yaml +lsp) :email (mu4e +gmail) :app calendar irc rss :config literate (default +bindings +smartparens))
        packages   ((calfw-cal :pin 8de82be1e67b6114e9661b55a92f996553a1da9d) (org-mu4e :disable t))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by Bounga** [comment]
@hlissner ping?

**Comment by hlissner** [comment]
@Bounga Can you reproduce it in Emacs 27.1?

**Comment by lromor** [comment]
I can reproduce this in emacs 28, using the latest commit of swiper as you pointed out.

**Comment by Bounga** [comment]
Gonna try with Emacs 27.1 this weekend and let you know how it goes

**Comment by beojan** [comment]
I'm seeing this issue again right after updating doom.
