### ISSUE TITLE
Calendar module doesn't work out-of-the-box with example config provided

### ISSUE THREAD

**Issue by Bounga** [hlissner/doom-emacs#3331]
**What did you expect to happen?**
I assumed that `=calendar` command would start the calendar showing org entries, diary entries and gcal ones by copy / pasting the [provided config example](https://github.com/hlissner/doom-emacs/tree/develop/modules/app/calendar#changing-calendar-sources).

**What actually happened?**

It crashes because `cfw:cal-create-source` and `cfw:ical-create-source` aren't defined.

Too make it work as expected I had to:

- add the packages to `packages.el`

```elisp
(package! calfw-cal :pin "8de82be1e67b6114e9661b55a92f996553a1da9d")
(package! calfw-ical :pin "263d5f37fff53f16165f347ee86dd35e54a93693")
```
then `doom sync`. I was then able to configure calendars but there's one little gotcha, I had to require `calfw-cal` and `calfw-ical`:

```elisp
(after! calfw
  (require 'calfw-cal)
  (require 'calfw-ical)
  (defun +calendar/open-calendar ()
    "My calendar definition"
    (interactive)
    (cfw:open-calendar-buffer
     :contents-sources
     (list
      (cfw:org-create-source "Green")  ; orgmode source
      (cfw:cal-create-source "Orange") ; diary source
      (cfw:ical-create-source "gcal" "https://calendar.google.com/calendar/ical/…/basic.ics" "IndianRed")))))
```

**Steps to reproduce:**
1. enable `calendar` module,
2. copy / paste the provided config and change urls / filenames,
3. run `=calendar`.

**System information:**
<details>

```
emacs   version    28.0.50
        features   JPEG TIFF GIF PNG RSVG IMAGEMAGICK DBUS GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS XWIDGETS PDUMPER LCMS2 GMP
        build      Apr 24, 2020
        buildopts  (--enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-head/HEAD-bef617d_1/share/info/emacs --prefix=/usr/local/Cellar/emacs-head/HEAD-bef617d_1 --without-x --with-dbus --with-imagemagick --with-modules --without-pop --with-gnutls --with-rsvg --with-xml2 --with-xwidgets --with-harfbuzz --with-ns --disable-ns-self-contained)
        windowsys  ns
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop 87364138d 2020-06-03 03:46:58 -0400
        dir        ~/.doom.d/
system  type       darwin
        config     x86_64-apple-darwin19.3.0
        shell      /usr/local/bin/fish
        uname      Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
        path       (~/.rbenv/shims ~/bin/elixir-ls/ /usr/local/MacGPG2/bin /Library/TeX/texbin /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/sbin /sbin /usr/local/Cellar/emacs-head/HEAD-bef617d_1/libexec/emacs/28.0.50/x86_64-apple-darwin19.3.0/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company (ivy +icons) :ui doom doom-dashboard hl-todo modeline ophints (popup +defaults) treemacs vc-gutter window-select workspaces zen :editor file-templates (format +onsave) objed snippets :emacs (dired +icons) electric (ibuffer +icons) undo vc :term eshell vterm :checkers syntax (spell +everywhere) grammar :tools debugger docker (eval +overlay) gist (lookup +docsets +dictionary +xwidget) (lsp +peek) macos (magit +forge) pass pdf :lang (cc +lsp) (elixir +lsp) emacs-lisp json (javascript +lsp) markdown (org +pandoc +present) plantuml (ruby +rbenv +rails +lsp) sh (web +lsp) (yaml +lsp) :email (mu4e +gmail) :app calendar irc rss :config (default +bindings +smartparens))
        packages   ((calfw-cal :pin 8de82be1e67b6114e9661b55a92f996553a1da9d) (calfw-ical :pin 263d5f37fff53f16165f347ee86dd35e54a93693))
        unpin      (n/a)
        elpa       (n/a)
```
</details>

**Comment by hlissner** [comment]
This was resolved by #3388. Let me know if that isn't the case and I'll reopen the issue. Thanks for bringing it to my attention!

**Comment by Bounga** [comment]
Hi @hlissner I tried the latest version but the fix only solves half of the issue.

It does load the `calfw-ical` package / command but not the `calfw-cal` one so now we can configure ical source but still can't define cal one so I can't load my diary source for example.

**Comment by Bounga** [comment]
I created a PR to fix this remaining issue.
