### ISSUE TITLE
Weird indentation when you safe an j2 template file

### ISSUE THREAD

**Issue by nardusg** [hlissner/doom-emacs#3555]
**What did you expect to happen?**
The indentation should not change

**What actually happened?**
It looks like it change, you have to undo and then save again.
The screencast should make it clear what is happening
![peek_opt](https://user-images.githubusercontent.com/29011858/87436338-34160200-c5ed-11ea-9214-6d60b1a4e18a.gif)

**System information:**
<details><pre>
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2
        build      Jan 28, 2020
        buildopts  (--build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-dbus --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xft --with-xpm --with-x-toolkit=gtk3 --with-gpm=no --with-xwidgets --with-modules build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu 'CFLAGS=-DMAIL_USE_LOCKF -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' LDFLAGS=-Wl,-z,relro PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop ff0b78e0b 2020-07-13 17:18:19 -0400
        dir        ~/emacs_configs/doom-emacs/.doom.d/
system  type       gnu/linux
        config     x86_64-redhat-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.7.8-200.fc32.x86_64 #1 SMP Thu Jul 9 14:34:51 UTC 2020 x86_64
        path       (~/emacs_configs/doom-emacs/.emacs.d/bin/../bin /usr/share/Modules/bin /usr/local/bin /usr/local/sbin /usr/bin /usr/sbin ~/bin ~/emacs_configs/doom-emacs/.emacs.d/bin ~/.local/bin /usr/libexec/emacs/26.3/x86_64-redhat-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion company (ivy +childframe +icons) :ui deft doom doom-dashboard doom-quit hl-todo indent-guides modeline nav-flash ophints (popup +defaults) tabs treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold multiple-cursors rotate-text snippets :emacs (dired +icons) electric ibuffer undo vc :term eshell vterm :checkers syntax spell :tools ansible docker editorconfig (eval +overlay) (lookup +docsets) lsp (magit +forge) pdf upload :lang data emacs-lisp markdown (org +dragndrop +hugo +present +journal +roam) raku (python +lsp) sh yaml :app calendar :config literate (default +bindings +smartparens))
        packages   ((counsel-tramp) (docker-tramp) (kubernetes-tramp) (emojify) (mixed-pitch) (ace-link) (telega) (nov) (company-org-roam) (org-alert) (org-ref) (org-bullets) (org-jira) (tracking) (rainbow-identifiers) (beacon) (zoom) (org-roam-bibtex) (ivy-bibtex))
        unpin      (n/a)
        elpa       (n/a)
```
</details>
</pre></details>

**Comment by zeronone** [comment]
It was due to `:tools ansible` for me.

**Comment by hlissner** [comment]
Appears to be an upstream issues. [These lines](https://github.com/paradoxxxzero/jinja2-mode/blob/master/jinja2-mode.el#L326-L328) are the cause, and [an issue already exists about it](https://github.com/paradoxxxzero/jinja2-mode/issues/16).

Since it doesn't seem to be maintained anymore, I doubt it'll be fixed, so I've fixed this here, in 576eb40. Thanks for bringing it to my attention.

**Comment by seanfarley** [comment]
For some reason, this fix sporadically doesn't work for me. Even with it, I still have this in my `after-save-hook`:
```
(git-gutter
 flycheck-handle-save
 jinja2-indent-buffer
 t
 ws-butler-after-save)
```

Even re-running `jinja2-mode` doesn't get rid of it.

**Comment by seanfarley** [comment]
Also, https://github.com/paradoxxxzero/jinja2-mode/pull/20 was recently merged, hooray! So maybe this is fixed for good?

**Comment by hlissner** [comment]
This was fixed upstream, `:tools ansible` was bumped in #3619, and I've reverted my local "fix" in 47a350f, so I'll consider this resolved. Thanks for your help @seanfarley and for bringing this to my attention!
