### ISSUE TITLE
Doom-emacs uses unsupported and as a consequence uninstallable packages

### ISSUE THREAD

**Issue by igorvolnyi** [hlissner/doom-emacs#368]
Generally 'make install' finishes OK failing to install 5 packages. Just repeat 'make' command.

Make gives:
Looking for packages to install...
5 packages will be installed:

\+ ob-mongo (ELPA)
\+ ob-redis (ELPA)
\+ ob-translate (ELPA)
\+ ox-pandoc (ELPA)
\+ ox-reveal (ELPA)

Proceed? (y or n) y
Refreshing package archives
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443
Contacting host: elpa.gnu.org:443
Contacting host: melpa.org:443
Package refresh done
Installing ox-reveal
  FATAL ERROR: (error) Package ‘org-20150330’ is unavailable
Installing ox-pandoc
  FATAL ERROR: (error) Package ‘org-8.2’ is unavailable
Installing ob-translate
  FATAL ERROR: (error) Package ‘org-8’ is unavailable
Installing ob-redis
  FATAL ERROR: (error) Package ‘org-8’ is unavailable
Installing ob-mongo
  FATAL ERROR: (error) Package ‘org-8’ is unavailable
Finished!

All these failed packages have no-more-existing packages among their dependencies (MELPA).

My system is Arch. I tried both Arch repo emacs-25.3 and AUR emacs 27.0.50.

**Comment by hlissner** [comment]
Are you the `develop` or `master` branch? 

This issue was fixed on `develop` fairly recently, and should make its way into `master` next weekend.

**Comment by igorvolnyi** [comment]
Good. Not critical, so can be waited for.
By the way where to ask questions to make doom-emacs' FAQ bigger?

**Comment by hlissner** [comment]
At the moment, they come from questions [emailed to me](mailto:henrik@lissner.net) or asked in issues here. Feel free to open an issue just to ask questions, but if you have many questions to ask I'd prefer them by email!

**Comment by themad** [comment]
Just FYI, even on current =develop= (62dc472dfe0175a5d7e936f188f7b205b11b693b) =ob-redis= fails to install.  The other packages mentioned above work fine.

**Comment by hlissner** [comment]
@themad You are correct. It seems ob-redis has been merged into org upstream and removed from MELPA. I will remove it in `develop` soon.

**Comment by rudedogg** [comment]
Is the `develop` branch supposed to require Emacs 26? I would like to use doom-emacs and org-mode, so I tried using develop but I get the following when I run `make install`:
```shell
> make install
Installing company-childframe
  FATAL ERROR: (error Package ‘emacs-26.0’ is unavailable)
Installing ivy-posframe
  FATAL ERROR: (error Package ‘emacs-26.0’ is unavailable)
```

Starting emacs:
```lisp
Debugger entered--Lisp error: (error "The :ui posframe module requires Emacs 26+")
  signal(error ("The :ui posframe module requires Emacs 26+"))
  error("The :ui posframe module requires Emacs 26+")
  (progn (error "The :ui posframe module requires Emacs 26+"))
  (if (version< emacs-version "26") (progn (error "The :ui posframe module requires Emacs 26+")))
```

I'm using Emacs 25.3.1
```shell
> emacs --version
GNU Emacs 25.3.1
```

If this should go into a separate issue let me know and I'll enter it.

**Comment by hlissner** [comment]
@rudedogg Do you have your private module somewhere I can see it? Perhaps on github? 

And does running `make` resolve your issue?

Lastly, could you try running `make info` and copying that output here?

**Comment by rudedogg** [comment]
Thanks @hlissner for the quick reply.

I'm just getting going, so I don't have a private module setup.

Here's exactly what I'm running:
```shell
(recursive rm of ~/.emacs.d/)
git clone -b develop https://github.com/hlissner/doom-emacs ~/.emacs.d
cd ~/.emacs.d
cp init.example.el init.el
(edit init.el to comment out `posframe`)
make install
(start emacs)
```

`make install` finishes without any errors. But, when I load Emacs it's plain like it can't load the config.

Running `make` says no unused packages, and no packages to install. I still get the `Recursive load` message and a plain emacs window though.

-----------------------------

`make info` output:
```
> make info
Symbol’s value as variable is void: doom-emacs-dir
make: *** [info] Error 255
```

**Comment by wdavew** [comment]
@rudedogg I had the same error and `make info` output as you when using emacs 25.3.1 on OSX. I just upgraded to version 26 and it works fine now. If you just want to get it working, that might solve your issue. 

I am using this on arch linux as well, and it works fine there.

**Comment by hlissner** [comment]
@rudedogg @wdavew Four days ago, I pushed c760b33212ed5ee531b45f90a386cde96fce7394, which fixes a bug where enabling a non-existent module would cause a recursive load error. Please let me know if this addresses your issues.

**Comment by rudedogg** [comment]
@wdavew Thanks for the tips. I tried the version 26.0.91-1, and nightly build on https://emacsformacosx.com/builds but still had issues :(.

I dual boot Antergos, so I installed doom-emacs there and had no issues at all.

@hlissner No luck unfortunately. I'm at d07495e62, and getting the following:
```
file-readable-p: Recursive load: "/Users/rudedogg/.emacs.d/modules/feature/workspaces/autoload/workspaces.el", "/Users/rudedogg/.emacs.d/modules/feature/workspaces/autoload/workspaces.el", "/Users/rudedogg/.emacs.d/modules/feature/workspaces/autoload/workspaces.el", "/Users/rudedogg/.emacs.d/modules/feature/workspaces/autoload/workspaces.el", "/Users/rudedogg/.emacs.d/modules/feature/workspaces/autoload/workspaces.el", "/usr/local/Cellar/emacs-plus/25.3/share/emacs/25.3/lisp/emacs-lisp/warnings.elc"
mwheel-scroll: End of buffer
```
----------------------

```shell
DOOM Doctor
Emacs v25.3.1
Doom v2.0.9
Commit d07495e62690355702edf7bdf14a8866c95a0d5f
shell: /usr/local/bin/fish
Compiled with: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB
  TOOLKIT_SCROLL_BARS NS MODULES
uname -a: Darwin Austins-iMac.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec
  17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

----

test-emacs
test-windows
test-fonts
test-gnutls
test-tls
Validated https://elpa.gnu.org
Validated https://melpa.org
Successfully rejected https://self-signed.badssl.com
Successfully rejected https://wrong.host.badssl.com/
test-tar
Warning: BSD tar detected
  QUELPA (through package-build) uses the system tar to build plugins, but it
  expects GNU tar. BSD tar *could* cause errors during package installation or
  updating from non-ELPA sources.  MacOS users can install gnu-tar via homebrew:
  brew install gnu-tar

----
Attempt to load DOOM: failed (Cannot open load file No such file or
  directory evil-collection-package-menu)
test-modules
  test-module -> :feature eval
  > Syntax error: (error package.el is not yet initialized!)

...
```

**Comment by hlissner** [comment]
@rudedogg Did you run `make` after updating? This looks like a cache issue. Otherwise, could you try manually deleting `~/.emacs.d/.local/packages.el`?

**Comment by rudedogg** [comment]
Still no luck :(. Getting the same errors in emacs and `make info` output.

**Comment by orther** [comment]
I was having issues like this and couldn't figure out why. I ended up removing `.local` folder altogether (which will remove cache you may not want to lose) and everything installed when I ran `make`.
