### ISSUE TITLE
'doom sync' and 'doom upgrade' abort prematurely after "Restarting..."

### ISSUE THREAD

**Issue by TimQuelch** [hlissner/doom-emacs#3746]
Doom CLI does not work. It tangles the literate config and then restarts and does not execute further. I bisected and it looks like the first commit where this occurs is https://github.com/hlissner/doom-emacs/commit/eb9cb0c6e95c2f7ed2426b8238c21fe52ca21cf8

**What did you expect to happen?**
Executing `doom <cmd>` should do the thing.

**What actually happened?**
It does not do the thing, instead I get:
```
doom sync
> Compiling your literate config...
  - Tangled 66 code blocks from config.org.sQm9M6
  - Restarting...
```

**Additional details:**
- https://github.com/TimQuelch/emacs.d my config
- I'm using the fish shell, but I tried it in sh and bash and it still didn't seem to work. The diff seems to default to using `/usr/bin/env sh anyway`. It may be caused by the different way fish defines environment variables (e.g. `env NOTANGLE=1 doom ...` rather than just `NOTANGLE=1 doom ...`)

**Steps to reproduce:**
1. Have a literate config,
2. checkout `develop` or https://github.com/hlissner/doom-emacs/commit/eb9cb0c6e95c2f7ed2426b8238c21fe52ca21cf8
3. `doom sync`

**System information:**
<details><pre>
> Compiling your literate config...
  - Tangled 66 code blocks from config.org.W3Dj7m
((emacs
  (version . "27.1")
  (features . "XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD PDUMPER LCMS2 GMP")
  (build . "Aug 12, 2020")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp))
 (doom
  (version . "2.0.9")
  (build . "HEAD, refs/bisect/good-3173b39b587e9f4f43b888f2ce6a3a0c9800cc96 3173b39b5 2020-08-09 01:50:41 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 5.4.55-1-lts #1 SMP Fri, 31 Jul 2020 17:38:35 +0000 x86_64")
  (path "~/bin" "~/.local/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/opt/cuda/bin" "/var/lib/flatpak/exports/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/opt/cuda/bin" "/var/lib/flatpak/exports/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/lib/emacs/27.1/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion (company +childframe) (helm +fuzzy) :ui doom modeline nav-flash ophints (popup +all +defaults) pretty-code treemacs vc-gutter vi-tilde-fringe window-select :editor (evil +everywhere) (format +onsave) :emacs (dired +icons) electric vc undo :term vterm :checkers syntax spell :tools (eval +overlay) docker lookup (lsp +peek) (magit +forge) pdf :lang (cc +lsp) emacs-lisp data json latex markdown (org +jupyter +noter +roam +journal) (python +lsp) (sh +fish) :config literate (default +bindings +smartparens))
  (packages (visual-fill-column) (mixed-pitch) (comment-dwim-2) (org-super-agenda) (org-ref) (helm-bibtex) (org-roam :recipe (:host github :repo "org-roam/org-roam")) (org-roam-bibtex :recipe (:host github :repo "org-roam/org-roam-bibtex")) (org-noter) (nov) (notmuch) (org-msg :recipe (:host github :repo "TimQuelch/org-msg")) (helm-notmuch) (systemd) (docker-compose-mode))
  (unpin org-roam org-roam-bibtex org-roam-server)
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
My bad, there was a logic error in `+literate-tangle-h` preventing it from complet

**Comment by TimQuelch** [comment]
It simply exits back to the shell after the `Restarting...` line

**Comment by hlissner** [comment]
Does `~/.emacs.d/.local/.doom.sh` exist? And if it does... well, I'd ask you to send it to me, but it may contain sensitive information. Can you hop on [our Discord](https://discord.gg/qvGgnVx) and DM it to me?

**Comment by TimQuelch** [comment]
DMed

**Comment by Eiyeron** [comment]
Hello.

I'm having the same issue on Windows with the native 26.3 version, still occurring after 9a8fc46. The smallest reproducible configuration triggering the issue I can get is enabling the literate module and having a blank config.org (not having the file triggers an error).

I don't know if you support Windows setups, but I hope it could help you find the issue.

Have a nice day.

**Comment by TimQuelch** [comment]
Just tested with https://github.com/hlissner/doom-emacs/commit/9a8fc46c7438d748caec92e4c1d689d7e98feea6, it doesn't seem to have fixed it

**Comment by limaco** [comment]
I have the same issue in ONE of TWO windows 10 machines; it seems to be somehow powershell related.

**Comment by limaco** [comment]
perhaps a EOL problem when creating ENV (.doom.sh)

Via Cygwin:

$ ./Doom sync
> Compiling your literate config...
  - Tangled 71 code blocks from config.org.OnONDj
  - Restarting...
./../.local/.doom.sh: línea 2: $'\r': no se encontró la orden
./../.local/.doom.sh: línea 3: $'\r': no se encontró la orden
./../.local/.doom.sh: línea 4: $'\r': no se encontró la orden
./../.local/.doom.sh: línea 5: $'\r': no se encontró la orden

**Comment by limaco** [comment]
So, after updating Doom on the computer in which sync worked, same problem:
PS C:\Users\carlos\.emacs.d\bin> ./Doom upgrade
> Compiling your literate config...
  - Tangled 71 code blocks from config.org.p2DVPg
> Preparing to upgrade Doom Emacs and its packages...
- A new version of Doom Emacs is available!

  Old revision: 8bbac4bfb3 (9 days ago)
  New revision: 8fa5b9406c (11 hours ago)

View the comparison diff in your browser? (y or n) n
Proceed with upgrade? (y or n) y
> Upgrading Doom Emacs...
  > Cleaning .elc files
    - [KNo elc files to clean
  - From https://github.com/hlissner/doom-emacs
   * branch                develop    -> FETCH_HEAD
   * [new branch]          develop    -> _upgrade/develop
- Reloading Doom Emacs
PS C:\Users\carlos\.emacs.d\bin> ./Doom sync
> Compiling your literate config...
  - Tangled 71 code blocks from config.org.SwHU6K
  - Restarting...

**Comment by hlissner** [comment]
I'm likely making a bash-ist assumption in [these lines](https://github.com/hlissner/doom-emacs/blob/develop/bin/doom#L6-L10). If a windows user who is bash-savvy can take a look at these, perhaps experiment with them, it'd be a huge help.

Alternatively, try modifying [these two lines](https://github.com/hlissner/doom-emacs/blob/develop/core/core-cli.el#L174-L175):

```diff
-        (coding-system-for-write 'utf-8)
-        (coding-system-for-read  'utf-8))
+        (coding-system-for-write 'utf-8-unix)
+        (coding-system-for-read  'utf-8-unix))
```

And make sure `~/.emacs.d/.local/.doom.sh` does not exist when you next run `doom sync`.

**Comment by limaco** [comment]
Same result with powershell.
Cygwin Different output; had to dos2unix /.emacs.d/bin contents otherwise:
$ ./Doom sync
./Doom: línea 5: error sintáctico cerca del elemento inesperado `newline'
./Doom: línea 5: `:; case "$_VERSION" in *\ 2[0-5].[0-9]) echo "Detected Emacs $'VERSION"; echo "Doom only supports Emacs 26.1 and newer"; echo; exit 2 ;; esac


After dos2unix the files:
$ ./Doom sync
> Compiling your literate config...
  - Tangled 71 code blocks from config.org.b0KzK6
  - Restarting...
./../.local/.doom.sh: línea 69: rm: no se encontró la orden
/usr/bin/env: «sh»: No such file or directory

**Comment by hlissner** [comment]
9f45561 introduces a potential fix for this issue. Please give it a try.

**Comment by TimQuelch** [comment]
https://github.com/hlissner/doom-emacs/commit/9f4556182568fe84fb5aa11902d8b7b33dbb752c  and https://github.com/hlissner/doom-emacs/commit/b2120e21eb1eee972a0fa6fcd11f941bb4954b34 did not fix the issue for me

**Comment by limaco** [comment]
No success, BUT
a combination of [9f45561]( #https://github.com/hlissner/doom-emacs/commit/9f4556182568fe84fb5aa11902d8b7b33dbb752c) and [b2120e2](#https://github.com/hlissner/doom-emacs/commit/b2120e21eb1eee972a0fa6fcd11f941bb4954b34) with the previous patch 
```diff
-        (coding-system-for-write 'utf-8)
-        (coding-system-for-read  'utf-8))
+        (coding-system-for-write 'utf-8-unix)
+        (coding-system-for-read  'utf-8-unix))
```
narrows down the error to:
 
```
  - Tangled 71 code blocks from config.org.xPWrDN
  - Restarting...
/usr/bin/env: «sh»: No such file or ``directory
```
so manually removing line 185 of core-cli.el:
```
- "/usr/bin/env sh <<" delimiter "\n"
```
produces an _almost_ succesful execution of ./Doom sync command in Cygwin, since all the rm commands are ignored

```
./../.local/.doom.sh: línea 1: rm: no se encontró la orden
```
therefore entering in a loop update (after the fifth loop it just stopped,  although not in the expected procedure:

```
[...]
    > Byte-compiling autoloads file...
    ←[32mâo" Generated .local/autoloads.elc←[0m
  - Restart Emacs or use 'M-x doom/reload' for changes to take effect
←[32mâo" Finished! (33.1774s)←[0m
./../.local/.doom.sh: línea 1: rm: no se encontró la orden
> Compiling your literate config...
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "~/.emacs.d/.local/env"
    - Ignoring TERM=xterm
    - Ignoring HOME=C:\Users\Carlos
    ←[32mâo" Successfully generated "~/.emacs.d/.local/env"←[0m
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
    ←[32mâo" No packages need rebuilding←[0m
  > Purging orphaned packages (for the emperor)...
    - No builds to purge
    - Skipping elpa packages
    - Skipping repos
    - Skipping regrafting
  > (Re)generating autoloads file...
    > Generating autoloads file...


Carlos@Despacho-casa ~/.emacs.d/bin

```
I guess some conditional based on something like
```
(defconst *sys/win32*
  (eq system-type 'windows-nt))
```
perhaps could do the job, but I'm not an expert.

PowerShell, on the other hand, just stops as op said, probably because the rm command error. As far as PowerShell doesn't provide enough verbosity, I'm just guessing here.

**Comment by limaco** [comment]
ok, all of the above was manually made from the suggestions in this thread. After a ./Doom upgrade, sync works in PowerShell;
Just a minor error "ript":
```
PS C:\Users\Carlos\.emacs.d\bin> ./Doom upgrade -f
> Preparing to upgrade Doom Emacs and its packages...
- You have local modifications in Doom's source. Discarding them...
- A new version of Doom Emacs is available!

  Old revision: 702fb6e95d (5 days ago)
  New revision: 4bc70a8537 (37 minutes ago)

View the comparison diff in your browser? (y or n) y
- Opened github in your browser.
Proceed with upgrade? (y or n) y
> Upgrading Doom Emacs...
  > Cleaning .elc files
    - ←[KNo elc files to clean
  - From https://github.com/hlissner/doom-emacs
   * branch                develop    -> FETCH_HEAD
   * [new branch]          develop    -> _upgrade/develop
- Reloading Doom Emacs
"ript" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

PS C:\Users\Carlos\.emacs.d\bin> ./Doom sync
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "~/.emacs.d/.local/env"
    - Ignoring PROMPT=$P$G
    - Ignoring HOME=C:\Users\Carlos
    ←[32mâo" Successfully generated "~/.emacs.d/.local/env"←[0m
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
    ←[32mâo" No packages need rebuilding←[0m
  > Purging orphaned packages (for the emperor)...
    - No builds to purge
    - Skipping elpa packages
    - Skipping repos
    - Skipping regrafting
  > (Re)generating autoloads file...
    > Generating autoloads file...
    > Byte-compiling autoloads file...
    ←[32mâo" Generated .local/autoloads.elc←[0m
  - Restart Emacs or use 'M-x doom/reload' for changes to take effect
←[32mâo" Finished! (32.6765s)←[0m
```
As far as I'm concerned, the issue is solved.

**Comment by hlissner** [comment]
@TimQuelch Just pushed bb1e224. See if that fixes it for you.

**Comment by hlissner** [comment]
@limaco Are you doing any of this in git-bash? I don't think I can or will support powershell. Cygwin, however, should work, and I can't understand why it can't find `rm`.

Please run the following command in each of git-bash, powershell and cygwin:

```sh
echo $PATH
```

**Comment by limaco** [comment]
Git bash:
```
$ tr ':' '\n' <<< "$PATH"
/c/Users/Carlos/bin
/mingw64/bin
/usr/local/bin
/usr/bin
/bin
/mingw64/bin
/usr/bin
/c/Users/Carlos/bin
/c/Program Files (x86)/Common Files/Oracle/Java/javapath
/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler
/c/Windows/system32
/c/Windows
/c/Windows/System32/Wbem
/c/Windows/System32/WindowsPowerShell/v1.0
/c/Windows/System32/OpenSSH
/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common
/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR
/c/Program Files/Microsoft VS Code/bin
/cmd
/c/Program Files (x86)/GnuPG/bin
/c/Packages/bin
/c/Program Files/Calibre2
/c/Program Files/PuTTY
/c/Program Files/AutoFirma/AutoFirma
/c/Program Files/Common Files/Autodesk Shared
/c/Program Files/Microsoft SQL Server/120/Tools/Binn
/c/emacs/bin
/c/Packages/fd
/c/Packages/ripgrep
/c/Users/Carlos/.emacs.d/bin
/c/Program Files/Pandoc
/c/Users/Carlos/.emacs.d
/c/Users/Carlos/AppData/Local/Microsoft/WindowsApps
/c/texlive/2020/bin/win32
/c/Users/Carlos/AppData/Local/GitHubDesktop/bin
/c/Users/Carlos/.emacs.d/server
/usr/bin/vendor_perl
/usr/bin/core_perl
```
Cygwin:
```
$ echo -e ${PATH//:/\\n}
/usr/local/bin
/usr/bin
/cygdrive/c/Program Files (x86)/Common Files/Oracle/Java/javapath
/cygdrive/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler
/cygdrive/c/Windows/system32
/cygdrive/c/Windows
/cygdrive/c/Windows/System32/Wbem
/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0
/cygdrive/c/Windows/System32/OpenSSH
/cygdrive/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common
/cygdrive/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR
/cygdrive/c/Program Files/Microsoft VS Code/bin
/cygdrive/c/Program Files/Git/cmd
/cygdrive/c/Program Files (x86)/GnuPG/bin
/cygdrive/c/Packages/bin
/cygdrive/c/Program Files/Calibre2
/cygdrive/c/Program Files/PuTTY
/cygdrive/c/Program Files/AutoFirma/AutoFirma
/cygdrive/c/Program Files/Common Files/Autodesk Shared
/cygdrive/c/Program Files/Microsoft SQL Server/120/Tools/Binn
/cygdrive/c/emacs/bin
/cygdrive/c/Packages/fd
/cygdrive/c/Packages/ripgrep
/cygdrive/c/Users/Carlos/.emacs.d/bin
/cygdrive/c/Program Files/Pandoc
/cygdrive/c/Users/Carlos/.emacs.d
/cygdrive/c/Users/Carlos/AppData/Local/Microsoft/WindowsApps
/cygdrive/c/texlive/2020/bin/win32
/cygdrive/c/Users/Carlos/AppData/Local/GitHubDesktop/bin
/cygdrive/c/Users/Carlos/.emacs.d/server
```
PowerShell:
```
PS C:\Users\Carlos> $env:path -split ";"
C:\Program Files (x86)\Common Files\Oracle\Java\javapath
C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
C:\Program Files\Microsoft VS Code\bin
C:\Program Files\Git\cmd
C:\Program Files (x86)\Gpg4win\..\GnuPG\bin
C:\Packages\bin
C:\Program Files\Calibre2\
C:\Program Files\PuTTY\
C:\Program Files\AutoFirma\AutoFirma
C:\Program Files\Common Files\Autodesk Shared\
C:\Program Files\Microsoft SQL Server\120\Tools\Binn\
C:\emacs\bin
C:\Packages\fd
C:\Packages\ripgrep
C:\Users\Carlos\.emacs.d\bin
C:\Program Files\Pandoc\
C:\Users\Carlos\.emacs.d
C:\Users\Carlos\AppData\Local\Microsoft\WindowsApps
C:\texlive\2020\bin\win32
C:\Users\Carlos\AppData\Local\GitHubDesktop\bin
C:\Users\Carlos\.emacs.d\server
```
Powershell with WSL2 (UBUNTU):
```
PS C:\Users\Carlos> bash
carlos@Despacho-casa:/mnt/c/Users/Carlos$ echo -e ${PATH//:/\\n}
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/usr/games
/usr/local/games
/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath
/mnt/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler
/mnt/c/Windows/system32
/mnt/c/Windows
/mnt/c/Windows/System32/Wbem
/mnt/c/Windows/System32/WindowsPowerShell/v1.0/
/mnt/c/Windows/System32/OpenSSH/
/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common
/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR
/mnt/c/Program Files/Microsoft VS Code/bin
/mnt/c/Program Files/Git/cmd
/mnt/c/Program Files (x86)/GnuPG/bin
/mnt/c/Packages/bin
/mnt/c/Program Files/Calibre2/
/mnt/c/Program Files/PuTTY/
/mnt/c/Program Files/AutoFirma/AutoFirma
/mnt/c/Program Files/Common Files/Autodesk Shared/
/mnt/c/Program Files/Microsoft SQL Server/120/Tools/Binn/
/mnt/c/emacs/bin
/mnt/c/Packages/fd
/mnt/c/Packages/ripgrep
/mnt/c/Users/Carlos/.emacs.d/bin
/mnt/c/Program Files/Pandoc/
/mnt/c/Users/Carlos/.emacs.d
/mnt/c/Users/Carlos/AppData/Local/Microsoft/WindowsApps
/mnt/c/texlive/2020/bin/win32
/mnt/c/Users/Carlos/AppData/Local/GitHubDesktop/bin
/mnt/c/Users/Carlos/.emacs.d/server
/snap/bin
```

**Comment by hlissner** [comment]
8402f8a may fix this issue. Give it a try.

**Comment by limaco** [comment]
```
Carlos@Despacho-casa ~/.emacs.d/bin
$ ./Doom sync
> Compiling your literate config...
  - Tangled 71 code blocks from config.org.2ydlyu
  - Restarting...
./../.local/.doom.sh: línea 3: rm: no se encontró la orden
/usr/bin/env: «sh»: No such file or directory
```
rm exists and is accessible:
```
Carlos@Despacho-casa ~/.emacs.d/bin
$ touch test

Carlos@Despacho-casa ~/.emacs.d/bin
$ ls
doom  doom.cmd  org-capture  org-tangle  test

Carlos@Despacho-casa ~/.emacs.d/bin
$ rm -f test

Carlos@Despacho-casa ~/.emacs.d/bin
$ ls
doom  doom.cmd  org-capture  org-tangle
```

**Comment by hlissner** [comment]
> /usr/bin/env: «sh»: No such file or directory

@limaco Doesn't seem like you updated to 8402f8a.

**Comment by limaco** [comment]
I have:

```
PS C:\Users\Carlos\.emacs.d\bin> ./Doom upgrade -f
> Preparing to upgrade Doom Emacs and its packages...
- You have local modifications in Doom's source. Discarding them...
- A new version of Doom Emacs is available!

  Old revision: 702fb6e95d (6 days ago)
  New revision: 8402f8aecc (25 minutes ago)

View the comparison diff in your browser? (y or n) y
- Opened github in your browser.
Proceed with upgrade? (y or n) y
> Upgrading Doom Emacs...
  > Cleaning .elc files
    - ←[KNo elc files to clean
  - From https://github.com/hlissner/doom-emacs
   * branch                develop    -> FETCH_HEAD
   * [new branch]          develop    -> _upgrade/develop
- Reloading Doom Emacs
"ript" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
PS C:\Users\Carlos\.emacs.d\bin> ./Doom sync
> Compiling your literate config...
  - Tangled 71 code blocks from config.org.X8NZgs
  - Restarting...
PS C:\Users\Carlos\.emacs.d\bin>
'''

**Comment by hlissner** [comment]
Try b4431dc. Should hopefully fix the rm issue.

Though, I don't understand why you're getting an error about `ript`. Doom doesn't call any such program.

**Comment by hlissner** [comment]
@TimQuelch Has any of the recent commits fixed your issue?

**Comment by limaco** [comment]
ok, this is strange; cygwin didn't detect the previous update. Anyway, the same exact results:

```
$ ./Doom upgrade -f
> Preparing to upgrade Doom Emacs and its packages...
- You have local modifications in Doom's source. Discarding them...
- A new version of Doom Emacs is available!

  Old revision: 702fb6e95d (6 days ago)
  New revision: b4431dcd49 (23 minutes ago)

View the comparison diff in your browser? (y or n) n
Proceed with upgrade? (y or n) y
> Upgrading Doom Emacs...
  > Cleaning .elc files
    - ←[KNo elc files to clean
  - From https://github.com/hlissner/doom-emacs
   * branch                develop    -> FETCH_HEAD
   * [new branch]          develop    -> _upgrade/develop
- Reloading Doom Emacs
./../.local/.doom.sh: línea 3: rm: no se encontró la orden
./../.local/.doom.sh: línea 4: doom: no se encontró la orden

Carlos@Despacho-casa ~/.emacs.d/bin
$ ^C

Carlos@Despacho-casa ~/.emacs.d/bin
$ ./Doom sync
./Doom: línea 5: error sintáctico cerca del elemento inesperado `newline'
./Doom: línea 5: `:; case "$_VERSION" in *\ 2[0-5].[0-9]) echo "Detected Emacs $'VERSION"; echo "Doom only supports Emacs 26.1 and newer"; echo; exit 2 ;; esac

Carlos@Despacho-casa ~/.emacs.d/bin
$ ./Doom sync
> Compiling your literate config...
  - Tangled 71 code blocks from config.org.oBdf3p
  - Restarting...
./../.local/.doom.sh: línea 3: rm: no se encontró la orden
/usr/bin/env: «sh»: No such file or directory
``

**Comment by limaco** [comment]
> Try [b4431dc](https://github.com/hlissner/doom-emacs/commit/b4431dcd49ecf74de23463dfa15952462320dd45). Should hopefully fix the rm issue.
> 
> Though, I don't understand why you're getting an error about `ript`. Doom doesn't call any such program. Do you have a powershell config/initfile? It's not likely a Doom issue.

`ript` sounds like a partial call of some `script`. There is no config for powershell, as far as I know

**Comment by limaco** [comment]
The result of ./Doom sync WO literate (cygwin): 

```
$ ./Doom sync
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file at "~/.emacs.d/.local/env"
    - Ignoring TERM=xterm
    - Ignoring HOME=C:\Users\Carlos
    ←[32mâo" Successfully generated "~/.emacs.d/.local/env"←[0m
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
    ←[32mâo" No packages need rebuilding←[0m
  > Purging orphaned packages (for the emperor)...
    - No builds to purge
    - Skipping elpa packages
    - Skipping repos
    - Skipping regrafting
  > (Re)generating autoloads file...
    > Generating autoloads file...
    > Byte-compiling autoloads file...
    ←[32mâo" Generated .local/autoloads.elc←[0m
  - Restart Emacs or use 'M-x doom/reload' for changes to take effect
←[32mâo" Finished! (33.4875s)←[0m
./../.local/.doom.sh: línea 3: rm: no se encontró la orden
/usr/bin/env: «sh»: No such file or directory

'''

**Comment by limaco** [comment]
> > Try [b4431dc](https://github.com/hlissner/doom-emacs/commit/b4431dcd49ecf74de23463dfa15952462320dd45). Should hopefully fix the rm issue.
> > Though, I don't understand why you're getting an error about `ript`. Doom doesn't call any such program. Do you have a powershell config/initfile? It's not likely a Doom issue.
> 
> `ript` sounds like a partial call of some `script`. There is no config for powershell, as far as I know

173 core-cli.el:

``` 
post-script
```
`ript`?

**Comment by hlissner** [comment]
I'm stumped. @limaco Please create a new issue. I think yours is unrelated to the original issue.

Since Windows users on our Discord tell me this has fixed the original issue I'll close this thread.

**Comment by TimQuelch** [comment]
@hlissner No, none of these commits seem to have fixed it for me. The behaviour is still the same. 

However, following the advice seomeone on discord, It looks like I can get it working by running the doom executable directly, rather than through my symlink to my path directory.

```
[I] ┬─[timquelch@epsilon:~]─[09:03:54]
╰─>$ ~/bin/doom
> Compiling your literate config...
  - Tangled 66 code blocks from config.org.sA4M8H
  - Restarting...
[I] ┬─[timquelch@epsilon:~]─[09:04:02]
╰─>$ ls -lah bin/doom
lrwxrwxrwx 1 timquelch timquelch 20 Jun 22 13:57 bin/doom -> ../.emacs.d/bin/doom*
[N] ┬─[timquelch@epsilon:~]─[09:04:09]
╰─>$ ./.emacs.d/bin/doom
> Compiling your literate config...
  - Tangled 66 code blocks from config.org.Mb9RXQ
  - Restarting...
> Compiling your literate config...
Usage: doom [-hdy] [COMMAND]

A command line interface for managing Doom Emacs.

Includes package management, diagnostics, unit tests, and byte-compilation.
...
```

**Comment by limaco** [comment]
Not for me, but this is new
```
$ ./.emacs.d/bin/doom
/usr/bin/env: ‘sh\r’: No such file or directory
```

**Comment by hlissner** [comment]
@TimQuelch Ah. I had anticipated folks symlinking `~/.emacs.d`, but never `~/.emacs.d/bin/doom`. Any reason you don't add `~/.emacs.d/bin` to your `PATH` instead? I'm thinking windows' lack of native support for symlinks may be the cause here. Not sure how or if git bash makes sense of them.

@limaco Could you try running `doom sync && doom upgrade` from eshell instead of powershell? A discord member told me the odd `rm` issue (in powershell) went away after that. I can't make much sense of it.

**Comment by TimQuelch** [comment]
> Any reason you don't add `~/.emacs.d/bin` to your `PATH` instead?

I generally prefer to add things to my existing directories in PATH rather than modifying the actual PATH variable. Usually I have found that to be more stable (when moving systems, updating etc.). Not a hard philosophy though, so I'll definitely be adding .emacs.d/bin to PATH now.


> I'm thinking windows' lack of native support for symlinks may be the cause here

I am on linux

**Comment by Eiyeron** [comment]
Hello, even after updating to the commits after the one supposed to fix the issue and trying on clean installs, I still get the same issue, the script stopping at "reloading"

```
C:\Users\eiyer\AppData\Roaming>git clone https://github.com/hlissner/doom-emacs.git .emacs.d
Cloning into '.emacs.d'...
remote: Enumerating objects: 222, done.
remote: Counting objects: 100% (222/222), done.
remote: Compressing objects: 100% (151/151), done.
remote: Total 90753 (delta 114), reused 136 (delta 71), pack-reused 90531R
Receiving objects: 100% (90753/90753), 22.26 MiB | 2.84 MiB/s, done.
Resolving deltas: 100% (64073/64073), done.

C:\Users\eiyer\AppData\Roaming>doom install
Installing straight...
Cloning use-package...
Cloning use-package...done
Building use-package...
Building use-package -> Building bind-key...
Building use-package -> Building bind-key...done
Building use-package...
Building use-package...done

WARNING (:ui pretty-code) module was moved to (:ui ligatures)
> Compiling your literate config...
  - Tangled 23 code blocks from config.org.0NLxxZ
  - Restarting...

C:\Users\eiyer\AppData\Roaming>doom help
WARNING (:ui pretty-code) module was moved to (:ui ligatures)
> Compiling your literate config...
  - Tangled 23 code blocks from config.org.Bk44Gy
  - Restarting...
```

I always set windows to prefer cmd over powershell and my PATH is setup to add .emacs.d/bin and emacs' folders.

**Comment by timotheosh** [comment]
I have been symlinking both the doom and org-tangle executables. Still works for me on Linux, but apparently not on FreeBSD. I confirmed on FreeBSD, that if I run doom via the absolute path, it tangles and does its thing just fine.

**Comment by TimQuelch** [comment]
Just a note on the title change, this is not just for `doom sync` but for any `doom <command>`

**Comment by hlissner** [comment]
It only applies to commands that execute a post-script, which are `doom sync` (when the `:config literate` module is enabled) and `doom upgrade`.

I'm working on a fix.

**Comment by hlissner** [comment]
> I have been symlinking both the doom and org-tangle executables

I'll make it emit an error if `doom` itself is symlinked. Due to constraints with the bourne shell there's no reliable, portable way to determine the location of the script when symlinks are invovled (readlink isn't available on all systems).

**Comment by hlissner** [comment]
e632871 contains a hopeful fix for this issue. Please update and let me know if the situation has changed.

**Comment by hlissner** [comment]
As an alternative for folks that want to symlink the `bin/doom` script, I'd recommend a shim or alias instead:

e.g. in ~/bin/doom:

```elisp
#!/usr/bin/env sh
~/.emacs.d/bin/doom "$@"
```

Or your shell config:

```sh
alias doom=~/.emacs.d/bin/doom
```

**Comment by hlissner** [comment]
Actually, scratch that. 4fa0241 should allow bin/doom to be symlinked.

**Comment by Eiyeron** [comment]
Seems like it did the trick, my workstation's config works with HEAD like charm, I'll try at home later but I think it's fixed on my side, thanks for your work!

**Comment by limaco** [comment]
On windows no error, but it's not tangling (i.e. not generating config.el from config.org)
steps I followed:
set init.el to "literate"
delete config.el --> touch config.el
./doom sync
config.el --> 0 bytes

**Comment by hlissner** [comment]
@limaco 63a0384 should fix that.

**Comment by asymmetric** [comment]
@hlissner This now results in

```
/home/asymmetric/.emacs.d/bin/doom: line 7: [: : integer expression expected
```

**Comment by limaco** [comment]
```
PS C:\Users\Carlos> doom sync
> Compiling your literate config...
  - Tangled 71 code blocks from config.org.0wK91o
  - Restarting...
←[31mx There was an unexpected error←[0m
  ←[1mMessage:←[0m Wrong type argument
  ←[1mData:←[0m (wrong-type-argument arrayp nil)
  ←[1mBacktrace:←[0m
    (replace-regexp-in-string \(\\*\)" \1\1\\" nil)
    (shell-quote-argument nil)
    (insert #!/usr/bin/env sh
     _postscript() {
       rm -f  (shell-quote-argument scr
    (save-current-buffer (set-buffer temp-buffer) (insert #!/usr/bin/env sh
     _pos
    (prog1 (save-current-buffer (set-buffer temp-buffer) (insert #!/usr/bin/env
    (unwind-protect (prog1 (save-current-buffer (set-buffer temp-buffer) (insert
    (let ((temp-file script) (temp-buffer (get-buffer-create (generate-new-buffe
    (let ((script (getenv __DOOMPOST)) (coding-system-for-write (quote utf-8-uni
    ((lambda (command) (let ((script (getenv __DOOMPOST)) (coding-system-for-wri
    (funcall (lambda (command) (let ((script (getenv __DOOMPOST)) (coding-system
  ←[33m! Extended backtrace logged to ~/.emacs.d/.local/doom.error.log←[0m
No catch for tag: exit, 255
```

**Comment by hlissner** [comment]
@limaco That was in powershell? Git bash? And you've updated to 239516a?

**Comment by limaco** [comment]
Updated to the last version. It was powershell.

eshell produces the same result:
```
/c/Users/Carlos λ doom sync 
> Compiling your literate config...
  - Tangled 71 code blocks from config.org.RG0flD
  - Restarting...
x There was an unexpected error
  Message: Wrong type argument
  Data: (wrong-type-argument arrayp nil)
  Backtrace:
    (replace-regexp-in-string \(\\*\)" \1\1\\" nil)
    (shell-quote-argument nil)
    (insert #!/usr/bin/env sh
     _postscript() {
       rm -f  (shell-quote-argument scr
    (save-current-buffer (set-buffer temp-buffer) (insert #!/usr/bin/env sh
     _pos
    (prog1 (save-current-buffer (set-buffer temp-buffer) (insert #!/usr/bin/env 
    (unwind-protect (prog1 (save-current-buffer (set-buffer temp-buffer) (insert
    (let ((temp-file script) (temp-buffer (get-buffer-create (generate-new-buffe
    (let ((script (getenv __DOOMPOST)) (coding-system-for-write (quote utf-8-uni
    ((lambda (command) (let ((script (getenv __DOOMPOST)) (coding-system-for-wri
    (funcall (lambda (command) (let ((script (getenv __DOOMPOST)) (coding-system
  ! Extended backtrace logged to ~/.emacs.d/.local/doom.error.log
No catch for tag: exit, 255
```
Git bash results in a different error:
```
Carlos@Despacho-casa MINGW64 ~
$ doom sync
> Compiling your literate config...
  - Tangled 71 code blocks from config.org.zupF57
  - Restarting...
/tmp/doom.sh: line 6: SHELLOPTS: readonly variable
```

**Comment by hlissner** [comment]
@limaco Does 47b42a9 change anything?

**Comment by limaco** [comment]
No improvement; same result:
```
# -*- lisp-interaction -*-
# vim: set ft=lisp:

(wrong-type-argument (arrayp nil))

(replace-regexp-in-string "\\(\\\\*\\)\"" "\\1\\1\\\\\"" nil)

(shell-quote-argument nil)

(insert "#!/usr/bin/env sh\n" "_postscript() {\n" "  rm -f " (shell-quote-argument script) "\n  " (cond ((eq command :restart) "$@") ((stringp command) command) ((string-join (if (listp (car-safe command)) (let* ((--cl-var-- (doom-enlist command)) (line nil) (--cl-var-- nil)) (while (consp --cl-var--) (setq line (car --cl-var--)) (setq --cl-var-- (cons (mapconcat #'shell-quote-argument (remq nil line) " ") --cl-var--)) (setq --cl-var-- (cdr --cl-var--))) (nreverse --cl-var--)) (list (mapconcat #'shell-quote-argument (remq nil command) " "))) "\n  "))) "\n}\n" (let ((save-match-data-internal (match-data))) (unwind-protect (progn (let* ((--cl-var-- process-environment) (env nil) (--cl-var-- "")) (while (consp --cl-var--) (setq env (car --cl-var--)) (if (string-match "^\\([a-zA-Z0-9_]+\\)=\\(.+\\)$" env) (progn (setq --cl-var-- (concat --cl-var-- (format "%s=%s \\\n" (match-string 1 env) (shell-quote-argument (match-string 2 env))))))) (setq --cl-var-- (cdr --cl-var--))) --cl-var--)) (set-match-data save-match-data-internal 'evaporate))) (format "PATH=\"%s%s$PATH\" \\\n" (concat doom-emacs-dir "bin/") path-separator) "_postscript $@\n")

(save-current-buffer (set-buffer temp-buffer) (insert "#!/usr/bin/env sh\n" "_postscript() {\n" "  rm -f " (shell-quote-argument script) "\n  " (cond ((eq command :restart) "$@") ((stringp command) command) ((string-join (if (listp (car-safe command)) (let* ((--cl-var-- (doom-enlist command)) (line nil) (--cl-var-- nil)) (while (consp --cl-var--) (setq line (car --cl-var--)) (setq --cl-var-- (cons (mapconcat #'shell-quote-argument (remq nil line) " ") --cl-var--)) (setq --cl-var-- (cdr --cl-var--))) (nreverse --cl-var--)) (list (mapconcat #'shell-quote-argument (remq nil command) " "))) "\n  "))) "\n}\n" (let ((save-match-data-internal (match-data))) (unwind-protect (progn (let* ((--cl-var-- process-environment) (env nil) (--cl-var-- "")) (while (consp --cl-var--) (setq env (car --cl-var--)) (if (string-match "^\\([a-zA-Z0-9_]+\\)=\\(.+\\)$" env) (progn (setq --cl-var-- (concat --cl-var-- (format "%s=%s \\\n" (match-string 1 env) (shell-quote-argument (match-string 2 env))))))) (setq --cl-var-- (cdr --cl-var--))) --cl-var--)) (set-match-data save-match-data-internal 'evaporate))) (format "PATH=\"%s%s$PATH\" \\\n" (concat doom-emacs-dir "bin/") path-separator) "_postscript $@\n"))

(prog1 (save-current-buffer (set-buffer temp-buffer) (insert "#!/usr/bin/env sh\n" "_postscript() {\n" "  rm -f " (shell-quote-argument script) "\n  " (cond ((eq command :restart) "$@") ((stringp command) command) ((string-join (if (listp (car-safe command)) (let* ((--cl-var-- (doom-enlist command)) (line nil) (--cl-var-- nil)) (while (consp --cl-var--) (setq line (car --cl-var--)) (setq --cl-var-- (cons (mapconcat #'shell-quote-argument (remq nil line) " ") --cl-var--)) (setq --cl-var-- (cdr --cl-var--))) (nreverse --cl-var--)) (list (mapconcat #'shell-quote-argument (remq nil command) " "))) "\n  "))) "\n}\n" (let ((save-match-data-internal (match-data))) (unwind-protect (progn (let* ((--cl-var-- process-environment) (env nil) (--cl-var-- "")) (while (consp --cl-var--) (setq env (car --cl-var--)) (if (string-match "^\\([a-zA-Z0-9_]+\\)=\\(.+\\)$" env) (progn (setq --cl-var-- (concat --cl-var-- (format "%s=%s \\\n" (match-string 1 env) (shell-quote-argument (match-string 2 env))))))) (setq --cl-var-- (cdr --cl-var--))) --cl-var--)) (set-match-data save-match-data-internal 'evaporate))) (format "PATH=\"%s%s$PATH\" \\\n" (concat doom-emacs-dir "bin/") path-separator) "_postscript $@\n")) (save-current-buffer (set-buffer temp-buffer) (write-region nil nil temp-file nil 0)))

(unwind-protect (prog1 (save-current-buffer (set-buffer temp-buffer) (insert "#!/usr/bin/env sh\n" "_postscript() {\n" "  rm -f " (shell-quote-argument script) "\n  " (cond ((eq command :restart) "$@") ((stringp command) command) ((string-join (if (listp (car-safe command)) (let* ((--cl-var-- (doom-enlist command)) (line nil) (--cl-var-- nil)) (while (consp --cl-var--) (setq line (car --cl-var--)) (setq --cl-var-- (cons (mapconcat #'shell-quote-argument (remq nil line) " ") --cl-var--)) (setq --cl-var-- (cdr --cl-var--))) (nreverse --cl-var--)) (list (mapconcat #'shell-quote-argument (remq nil command) " "))) "\n  "))) "\n}\n" (let ((save-match-data-internal (match-data))) (unwind-protect (progn (let* ((--cl-var-- process-environment) (env nil) (--cl-var-- "")) (while (consp --cl-var--) (setq env (car --cl-var--)) (if (string-match "^\\([a-zA-Z0-9_]+\\)=\\(.+\\)$" env) (progn (setq --cl-var-- (concat --cl-var-- (format "%s=%s \\\n" (match-string 1 env) (shell-quote-argument (match-string 2 env))))))) (setq --cl-var-- (cdr --cl-var--))) --cl-var--)) (set-match-data save-match-data-internal 'evaporate))) (format "PATH=\"%s%s$PATH\" \\\n" (concat doom-emacs-dir "bin/") path-separator) "_postscript $@\n")) (save-current-buffer (set-buffer temp-buffer) (write-region nil nil temp-file nil 0))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))

(let ((temp-file script) (temp-buffer (get-buffer-create (generate-new-buffer-name " *temp file*")))) (unwind-protect (prog1 (save-current-buffer (set-buffer temp-buffer) (insert "#!/usr/bin/env sh\n" "_postscript() {\n" "  rm -f " (shell-quote-argument script) "\n  " (cond ((eq command :restart) "$@") ((stringp command) command) ((string-join (if (listp (car-safe command)) (let* ((--cl-var-- (doom-enlist command)) (line nil) (--cl-var-- nil)) (while (consp --cl-var--) (setq line (car --cl-var--)) (setq --cl-var-- (cons (mapconcat #'shell-quote-argument (remq nil line) " ") --cl-var--)) (setq --cl-var-- (cdr --cl-var--))) (nreverse --cl-var--)) (list (mapconcat #'shell-quote-argument (remq nil command) " "))) "\n  "))) "\n}\n" (let ((save-match-data-internal (match-data))) (unwind-protect (progn (let* ((--cl-var-- process-environment) (env nil) (--cl-var-- "")) (while (consp --cl-var--) (setq env (car --cl-var--)) (if (string-match "^\\([a-zA-Z0-9_]+\\)=\\(.+\\)$" env) (progn (setq --cl-var-- (concat --cl-var-- (format "%s=%s \\\n" (match-string 1 env) (shell-quote-argument (match-string 2 env))))))) (setq --cl-var-- (cdr --cl-var--))) --cl-var--)) (set-match-data save-match-data-internal 'evaporate))) (format "PATH=\"%s%s$PATH\" \\\n" (concat doom-emacs-dir "bin/") path-separator) "_postscript $@\n")) (save-current-buffer (set-buffer temp-buffer) (write-region nil nil temp-file nil 0))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))

(let ((script (getenv "__DOOMPOST")) (coding-system-for-write 'utf-8-unix) (coding-system-for-read 'utf-8-unix)) (let ((temp-file script) (temp-buffer (get-buffer-create (generate-new-buffer-name " *temp file*")))) (unwind-protect (prog1 (save-current-buffer (set-buffer temp-buffer) (insert "#!/usr/bin/env sh\n" "_postscript() {\n" "  rm -f " (shell-quote-argument script) "\n  " (cond ((eq command :restart) "$@") ((stringp command) command) ((string-join (if (listp (car-safe command)) (let* ((--cl-var-- (doom-enlist command)) (line nil) (--cl-var-- nil)) (while (consp --cl-var--) (setq line (car --cl-var--)) (setq --cl-var-- (cons (mapconcat #'shell-quote-argument (remq nil line) " ") --cl-var--)) (setq --cl-var-- (cdr --cl-var--))) (nreverse --cl-var--)) (list (mapconcat #'shell-quote-argument (remq nil command) " "))) "\n  "))) "\n}\n" (let ((save-match-data-internal (match-data))) (unwind-protect (progn (let* ((--cl-var-- process-environment) (env nil) (--cl-var-- "")) (while (consp --cl-var--) (setq env (car --cl-var--)) (if (string-match "^\\([a-zA-Z0-9_]+\\)=\\(.+\\)$" env) (progn (setq --cl-var-- (concat --cl-var-- (format "%s=%s \\\n" (match-string 1 env) (shell-quote-argument (match-string 2 env))))))) (setq --cl-var-- (cdr --cl-var--))) --cl-var--)) (set-match-data save-match-data-internal 'evaporate))) (format "PATH=\"%s%s$PATH\" \\\n" (concat doom-emacs-dir "bin/") path-separator) "_postscript $@\n")) (save-current-buffer (set-buffer temp-buffer) (write-region nil nil temp-file nil 0))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))) (set-file-modes script 448))

((lambda (command) (let ((script (getenv "__DOOMPOST")) (coding-system-for-write 'utf-8-unix) (coding-system-for-read 'utf-8-unix)) (let ((temp-file script) (temp-buffer (get-buffer-create (generate-new-buffer-name " *temp file*")))) (unwind-protect (prog1 (save-current-buffer (set-buffer temp-buffer) (insert "#!/usr/bin/env sh\n" "_postscript() {\n" "  rm -f " (shell-quote-argument script) "\n  " (cond ((eq command :restart) "$@") ((stringp command) command) ((string-join (if (listp (car-safe command)) (let* ((--cl-var-- (doom-enlist command)) (line nil) (--cl-var-- nil)) (while (consp --cl-var--) (setq line (car --cl-var--)) (setq --cl-var-- (cons (mapconcat #'shell-quote-argument (remq nil line) " ") --cl-var--)) (setq --cl-var-- (cdr --cl-var--))) (nreverse --cl-var--)) (list (mapconcat #'shell-quote-argument (remq nil command) " "))) "\n  "))) "\n}\n" (let ((save-match-data-internal (match-data))) (unwind-protect (progn (let* ((--cl-var-- process-environment) (env nil) (--cl-var-- "")) (while (consp --cl-var--) (setq env (car --cl-var--)) (if (string-match "^\\([a-zA-Z0-9_]+\\)=\\(.+\\)$" env) (progn (setq --cl-var-- (concat --cl-var-- (format "%s=%s \\\n" (match-string 1 env) (shell-quote-argument (match-string 2 env))))))) (setq --cl-var-- (cdr --cl-var--))) --cl-var--)) (set-match-data save-match-data-internal 'evaporate))) (format "PATH=\"%s%s$PATH\" \\\n" (concat doom-emacs-dir "bin/") path-separator) "_postscript $@\n")) (save-current-buffer (set-buffer temp-buffer) (write-region nil nil temp-file nil 0))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))) (set-file-modes script 448)) 128) "__NOTANGLE=1 $@")

(funcall (lambda (command) (let ((script (getenv "__DOOMPOST")) (coding-system-for-write 'utf-8-unix) (coding-system-for-read 'utf-8-unix)) (let ((temp-file script) (temp-buffer (get-buffer-create (generate-new-buffer-name " *temp file*")))) (unwind-protect (prog1 (save-current-buffer (set-buffer temp-buffer) (insert "#!/usr/bin/env sh\n" "_postscript() {\n" "  rm -f " (shell-quote-argument script) "\n  " (cond ((eq command :restart) "$@") ((stringp command) command) ((string-join (if (listp (car-safe command)) (let* ((--cl-var-- (doom-enlist command)) (line nil) (--cl-var-- nil)) (while (consp --cl-var--) (setq line (car --cl-var--)) (setq --cl-var-- (cons (mapconcat #'shell-quote-argument (remq nil line) " ") --cl-var--)) (setq --cl-var-- (cdr --cl-var--))) (nreverse --cl-var--)) (list (mapconcat #'shell-quote-argument (remq nil command) " "))) "\n  "))) "\n}\n" (let ((save-match-data-internal (match-data))) (unwind-protect (progn (let* ((--cl-var-- process-environment) (env nil) (--cl-var-- "")) (while (consp --cl-var--) (setq env (car --cl-var--)) (if (string-match "^\\([a-zA-Z0-9_]+\\)=\\(.+\\)$" env) (progn (setq --cl-var-- (concat --cl-var-- (format "%s=%s \\\n" (match-string 1 env) (shell-quote-argument (match-string 2 env))))))) (setq --cl-var-- (cdr --cl-var--))) --cl-var--)) (set-match-data save-match-data-internal 'evaporate))) (format "PATH=\"%s%s$PATH\" \\\n" (concat doom-emacs-dir "bin/") path-separator) "_postscript $@\n")) (save-current-buffer (set-buffer temp-buffer) (write-region nil nil temp-file nil 0))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))) (set-file-modes script 448)) 128) "__NOTANGLE=1 $@")

(cond ((integerp val) (let ((code val)) code)) ((or (consp val) (or (stringp val) (keywordp val))) (funcall pcase-0 val)) (t 0))

(let* ((val (apply #'doom-cli-execute :doom (cdr (member "--" argv)))) (pcase-0 #'(lambda (command) (let ((script (getenv "__DOOMPOST")) (coding-system-for-write 'utf-8-unix) (coding-system-for-read 'utf-8-unix)) (let ((temp-file script) (temp-buffer (get-buffer-create (generate-new-buffer-name " *temp file*")))) (unwind-protect (prog1 (save-current-buffer (set-buffer temp-buffer) (insert "#!/usr/bin/env sh\n" "_postscript() {\n" "  rm -f " (shell-quote-argument script) "\n  " (cond ((eq command :restart) "$@") ((stringp command) command) ((string-join (if (listp (car-safe command)) (let* ((--cl-var-- (doom-enlist command)) (line nil) (--cl-var-- nil)) (while (consp --cl-var--) (setq line (car --cl-var--)) (setq --cl-var-- (cons (mapconcat #'shell-quote-argument (remq nil line) " ") --cl-var--)) (setq --cl-var-- (cdr --cl-var--))) (nreverse --cl-var--)) (list (mapconcat #'shell-quote-argument (remq nil command) " "))) "\n  "))) "\n}\n" (let ((save-match-data-internal (match-data))) (unwind-protect (progn (let* ((--cl-var-- process-environment) (env nil) (--cl-var-- "")) (while (consp --cl-var--) (setq env (car --cl-var--)) (if (string-match "^\\([a-zA-Z0-9_]+\\)=\\(.+\\)$" env) (progn (setq --cl-var-- (concat --cl-var-- (format "%s=%s \\\n" (match-string 1 env) (shell-quote-argument (match-string 2 env))))))) (setq --cl-var-- (cdr --cl-var--))) --cl-var--)) (set-match-data save-match-data-internal 'evaporate))) (format "PATH=\"%s%s$PATH\" \\\n" (concat doom-emacs-dir "bin/") path-separator) "_postscript $@\n")) (save-current-buffer (set-buffer temp-buffer) (write-region nil nil temp-file nil 0))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))) (set-file-modes script 448)) 128))) (cond ((integerp val) (let ((code val)) code)) ((or (consp val) (or (stringp val) (keywordp val))) (funcall pcase-0 val)) (t 0)))

(kill-emacs (let* ((val (apply #'doom-cli-execute :doom (cdr (member "--" argv)))) (pcase-0 #'(lambda (command) (let ((script (getenv "__DOOMPOST")) (coding-system-for-write 'utf-8-unix) (coding-system-for-read 'utf-8-unix)) (let ((temp-file script) (temp-buffer (get-buffer-create (generate-new-buffer-name " *temp file*")))) (unwind-protect (prog1 (save-current-buffer (set-buffer temp-buffer) (insert "#!/usr/bin/env sh\n" "_postscript() {\n" "  rm -f " (shell-quote-argument script) "\n  " (cond ((eq command :restart) "$@") ((stringp command) command) ((string-join (if (listp (car-safe command)) (let* ((--cl-var-- (doom-enlist command)) (line nil) (--cl-var-- nil)) (while (consp --cl-var--) (setq line (car --cl-var--)) (setq --cl-var-- (cons (mapconcat #'shell-quote-argument (remq nil line) " ") --cl-var--)) (setq --cl-var-- (cdr --cl-var--))) (nreverse --cl-var--)) (list (mapconcat #'shell-quote-argument (remq nil command) " "))) "\n  "))) "\n}\n" (let ((save-match-data-internal (match-data))) (unwind-protect (progn (let* ((--cl-var-- process-environment) (env nil) (--cl-var-- "")) (while (consp --cl-var--) (setq env (car --cl-var--)) (if (string-match "^\\([a-zA-Z0-9_]+\\)=\\(.+\\)$" env) (progn (setq --cl-var-- (concat --cl-var-- (format "%s=%s \\\n" (match-string 1 env) (shell-quote-argument (match-string 2 env))))))) (setq --cl-var-- (cdr --cl-var--))) --cl-var--)) (set-match-data save-match-data-internal 'evaporate))) (format "PATH=\"%s%s$PATH\" \\\n" (concat doom-emacs-dir "bin/") path-separator) "_postscript $@\n")) (save-current-buffer (set-buffer temp-buffer) (write-region nil nil temp-file nil 0))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))) (set-file-modes script 448)) 128))) (cond ((integerp val) (let ((code val)) code)) ((or (consp val) (or (stringp val) (keywordp val))) (funcall pcase-0 val)) (t 0))))

(eval-buffer #<buffer  *load*> nil "c:/Users/carlos/.emacs.d/bin/doom" nil t)

(load-with-code-conversion "c:/Users/carlos/.emacs.d/bin/doom" "c:/Users/carlos/.emacs.d/bin/doom" nil t)

(load "c:/Users/carlos/.emacs.d/bin/doom" nil t t)

(command-line-1 ("-scriptload" ".\\doom" "--" "sync"))

(command-line)

(normal-top-level)
```

**Comment by hlissner** [comment]
@limaco Let's move your issue to #3844 since it is different from the original issue (i.e. the postscript not executing at all). Now that the original issue and regressions thereafter have been resolved, I will close this.

**Comment by limaco** [comment]
Well, the original issue was that in a windows system, when :config literate was enabled, any doom <command> script stopped inmediately after Tangling-->restarting. Now new errors arise, but the issue persists... It will be confusing for a newcomer to see the issue marked as resolved, as far as it is not, moreover when the title of the new subjet is "Error when trying to upgrade Doom", wich is not the case.

**Comment by hlissner** [comment]
@limaco I've renamed the other issue.

> the original issue was that in a windows system, when :config literate was enabled, any doom script stopped inmediately after Tangling-->restarting. Now new errors arise, but the issue persists

The original issue is different. While the OP only reported it happening on Windows, there were other reports for Linux and macOS on our Discord. This was because /bin/sh (on some systems) runs scripts in POSIX mode (tantamount to `set -e`), so when `emacs` returned a non-zero exit code, bin/doom would abort immediately, without executing the post-script. That was fixed in https://github.com/hlissner/doom-emacs/commit/63a03848a3e026498c2e25348b2288ccca2f7ad8.

Your issue, however, is new. A new error and windows specific.
