### ISSUE TITLE
set-electric! overwrites default electric-indent-chars.

### ISSUE THREAD

**Issue by Janfel** [hlissner/doom-emacs#4031]
I believe [these lines](https://github.com/hlissner/doom-emacs/blob/fd912f2ad9293bdce81b9e71c74e8e1958b57079/modules/emacs/electric/autoload.el#L24) should use `setq-local` instead of `setq` to avoid clobbering the default value of `electric-indent-chars` as `electric-indent-chars` is a `defvar` instead of a `defvar-local` (at least in 27.1).

That being said, the whole function looks like it could use a rework. These are some suggestions that came to mind:

*Non-breaking:*
- Use `derived-mode-p` instead of `(eq major-mode)`.
- Use `defun` instead of `lambda` and `fset`.

*Breaking:*
- Make the `modes` argument behave like the `hooks` argument to `setq-hook!`.
- Update the outdated naming conventions.
- Reimplement using just `add-hook` and `setq-hook!`.

**Comment by hlissner** [comment]
> I believe these lines should use setq-local instead of setq to avoid clobbering the default value of electric-indent-chars as electric-indent-chars is a defvar instead of a defvar-local (at least in 27.1).

Done.

> Use derived-mode-p instead of (eq major-mode).

The use of `eq` is intentional. `derived-mode-p` would cause electric config to be inherited by child modes we don't want them in. e.g. java-mode and php-mode (which are derived from c-mode), or emacs-lisp-mode when we only want to target lisp-mode, etc. I prefer it be explicit.

> Use defun instead of lambda and fset.

I don't think this adds any value. fset is used because `set-electric!` is not a macro. I can't interpolate a function name into a `defun` form without an `eval`  or changing `set-electric!` into a macro; neither of which I think are necessary. After all, a `defun` is just an `defalias` (basically an `fset`) and a `lambda`.

> Make the modes argument behave like the hooks argument to setq-hook!.

This cannot be trivially done unless `set-electric!` is a macro (or we abuse `eval`). As a function it convolutes the MODES argument. e.g. `(set-electric! '(x-mode y-mode) ...)` or `(set-electric! '(quote x-mode-hook y-mode-hook) ...)`.

> Update the outdated naming conventions.

Done.

> Reimplement using just add-hook and setq-hook!.

Again, the use of macros complicates things. I don't want to abuse `eval`s or change `set-electric!` into a macro because that would hurt its composibility and limit its use cases.

**Comment by Janfel** [comment]
> > Use defun instead of lambda and fset.
>
> I don't think this adds any value.

It makes the function display nicer in `helpful` buffers but that’s about it.

> If they want to overwrite the electric config, use `set-electric!`. Its config shouldn't be overwritten by unrelated operations.

I didnt’t think about it like that. That makes sense.

> > Make the `modes` argument behave like the `hooks` argument to `setq-hook!`.
> 
> This cannot be trivially done unless `set-electric!` is a macro (or we abuse `eval`)

It’s a bit inconsistent but I agree that `set-electric!` is better off staying a function.

I still have a few questions about the code. Nothing major, just to satisfy my curiosity:

1. Why use `cond` instead of `if`? Can `fset` fail somehow?
1. Why use `cl-destructuring-bind` inside the `lambda`? Wouldn’t it be faster to destructure `plist` only once?
1. Why use `(null (car-safe plist))` instead of just `(null plist)`? Can `plist` be anything other than a list?

**Comment by hlissner** [comment]
> Why use cond instead of if? Can fset fail somehow?

This is just personal preference. I think it's a tiny bit more concise when the first branch has multiple forms:

```lisp
(cond (condition
       (...)
       (...))
      ((...)
       (...))

;; versus

(if conditionn
    (progn   ;; <-- this
      (...)
      (...))
  (...)
  (...))
```

Also makes it a little easier to add additional branches in the future.

> Why use cl-destructuring-bind inside the lambda? Wouldn’t it be faster to destructure plist only once?

By procedural, side-by-side comparison, yes, marginally, but in practice this is faster because you're not likely to trigger more than one major mode's hook at a time, but it is very likely that multiple packages will be loaded all at once (multiple calls to `set-electric!` at once). This way it's less work to do at load time, and more when the major mode is activated.

But really, the difference is negligible in this case, so performance is hardly a concern here.

> Why use (null (car-safe plist)) instead of just (null plist)? Can plist be anything other than a list?

Plist is always a list and should never be null.

+ `(set-electric! 'some-mode :x 1 :y 2)` (plist = `(:x 1 :y 2)`)
+ `(set-electric! 'some-mode nil)` (plist = `(nil)`)
+ `(set-electric! 'some-mode)` (plist = `()` = `nil`)

The first and second use-cases are valid. The third is not (though there is no error handling for it atm).

`(nil)` is interpreted as "unset any previous electric settings for `some-mode`.

-----

Hope that helps!
