### ISSUE TITLE
error "Don’t know how to format org-mode code"

### ISSUE THREAD

**Issue by brianmcgillion** [hlissner/doom-emacs#4129]
**What did you expect to happen?**

Saving an org file should work

**What actually happened?**
error "Don’t know how to format org-mode code"

**Additional details:**

Started after updating to d1effe2ddd3293547216ee74e68db60ea06bcf05

<details><pre>
If an error message is involved include a backtrace of it.

Debugger entered--Lisp error: (error "Don’t know how to format org-mode code")
  signal(error ("Don’t know how to format org-mode code"))
  error("Don't know how to format %S code" org-mode)
  format-all-buffer()
  funcall-interactively(format-all-buffer)
  call-interactively(format-all-buffer)
  +format-buffer-h()
  run-hooks(before-save-hook)
  basic-save-buffer(nil)
  save-buffer()
  #f(compiled-function (&optional stay-with-capture) "Finalize the capture process.\nWith prefix argument STAY-WITH-CAPTURE, jump to the location of the\ncaptured item after finalizing." (interactive "P") #<bytecode 0x55611a1>)(nil)
  apply(#f(compiled-function (&optional stay-with-capture) "Finalize the capture process.\nWith prefix argument STAY-WITH-CAPTURE, jump to the location of the\ncaptured item after finalizing." (interactive "P") #<bytecode 0x55611a1>) nil)
  org-capture-finalize(nil)
  funcall-interactively(org-capture-finalize nil)
  call-interactively(org-capture-finalize nil nil)
  command-execute(org-capture-finalize)

**Steps to reproduce:**
Enable roam
configure a roam capture
perform a capture
Confirm the capture
Backtrace

**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
	config     x86_64-pc-linux-gnu
	shell      /bin/bash
	uname      Linux 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64
	path       (~/.pyenv/shims ~/.pyenv/bin ~/.local/bin ~/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin ~/.emacs.d/bin /snap/bin /var/lib/snapd/snap/bin /usr/lib/emacs/27.1/x86_64-linux-gnu)
EMACS   dir        ~/.emacs.d/
	version    27.1
	build      Sep 19, 2020
	buildopts  --build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/27.1/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/27.1/site-lisp:/usr/share/emacs/site-lisp --program-suffix=27 --with-modules --with-file-notification=inotify --with-mailutils --with-harfbuzz --with-json --with-x=yes --with-x-toolkit=gtk3 --with-lcms2 --with-cairo --with-xpm=yes --with-gif=yes --with-gnutls=yes --with-jpeg=yes --with-png=yes --with-tiff=yes --with-xwidgets 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs27-bifpWT/emacs27-27.1~1.git86d8d76aa3=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie'
	features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
	traits     (batch server-running envvar-file)
DOOM    dir        ~/.doom.d/
	version    2.0.9
	build      HEAD -> bibtex c10a09bc0 2020-10-22 09:35:31 +0400
	elc-files  182
	modules    (:completion (company +childframe) (helm +fuzzy) :ui doom doom-dashboard hl-todo hydra modeline nav-flash ophints (popup +defaults) treemacs unicode vc-gutter (window-select +numbers) workspaces zen :editor file-templates fold (format +onsave) snippets word-wrap :emacs (dired +icons) electric (ibuffer +icons) (undo +tree) vc :term eshell vterm :checkers (syntax +childframe) (spell +aspell +everywhere) grammar :tools biblio (debugger +lsp) docker editorconfig (eval +overlay) (lookup +dictionary +offline +wordnet +docsets) (lsp +peek) magit make pass pdf taskrunner :lang (cc +lsp) data emacs-lisp (go +lsp) latex markdown (org +dragndrop +pandoc +present +gnuplot +roam +noter) (python +lsp +pyenv) (sh +lsp) web :app (rss +org) :config literate (default +bindings +smartparens))
	packages   ((elfeed-goodies) (org-roam-server) (company-tabnine) (super-save) (crux) (imenu-anywhere) (atomic-chrome))
	unpin      (org-roam helm)
	elpa       (n/a)
```

Place the output of `M-x doom/info` or `~/.emacs.d/bin/doom info` here.
</pre></details>

**Comment by oatmealm** [comment]
I can confirm seeing same problem... lassik/emacs-format-all-the-code/issues/100

**Comment by flyingns** [comment]
I have the same problem. ;-(

**Comment by flyingns** [comment]
My org file contains some headlines with `:crypt:` as tags. Each time I edit and save it, the information is automatically encrypted to protect some of my personal privacy. Everything was normal before, but since a commit, every time you save after editing, you can always get the error message in the title, and it no longer automatically encodes the encrypted information.

```
Debugger entered--Lisp error: (error "Don’t know how to format org-mode code")
  signal(error ("Don’t know how to format org-mode code"))
  error("Don't know how to format %S code" org-mode)
  format-all-buffer()
  funcall-interactively(format-all-buffer)
  call-interactively(format-all-buffer)
  (if (and (eq major-mode 'org-mode) (org-in-src-block-p t)) (+format--org-region nil nil) (call-interactively (cond ((and +format-with-lsp (and (boundp 'lsp-mode) lsp-mode) (lsp-feature\? "textDocument/formatting")) #'lsp-format-buffer) ((and +format-with-lsp (and (boundp 'eglot--managed-mode) eglot--managed-mode) (eglot--server-capable :documentFormattingProvider)) #'eglot-format-buffer) (#'format-all-buffer))))
  +format-buffer-h()
  run-hooks(before-save-hook)
  basic-save-buffer(t)
  save-buffer(1)
  funcall-interactively(save-buffer 1)
  call-interactively(save-buffer nil nil)
  command-execute(save-buffer)
```

**Comment by aerojustaero** [comment]
Same here 

`Debugger entered--Lisp error: (error "Don’t know how to format org-mode code")
  signal(error ("Don’t know how to format org-mode code"))
  error("Don't know how to format %S code" org-mode)
  format-all-buffer()
  funcall-interactively(format-all-buffer)
  call-interactively(format-all-buffer)
  (if (and (eq major-mode (quote org-mode)) (org-in-src-block-p t)) (+format--org-region nil nil) (call-interactively (cond ((and +format-with-lsp (and (boundp (quote lsp-mode)) lsp-mode) (lsp-feature\? "textDocument/formatting")) (function lsp-format-buffer)) ((and +format-with-lsp (and (boundp (quote eglot--managed-mode)) eglot--managed-mode) (eglot--server-capable :documentFormattingProvider)) (function eglot-format-buffer)) ((function format-all-buffer)))))
  +format-buffer-h()
  run-hooks(before-save-hook)
  basic-save-buffer(t)
  save-buffer(1)
  funcall-interactively(save-buffer 1)
  call-interactively(save-buffer nil nil)
  command-execute(save-buffer)
`

**Comment by credmp** [comment]
Is this not related to the following package?

    (format +onsave)  ; automated prettiness

I enabled that to auto format my code, but it also seems to bring in this error message. The document saves just fine for me.

In @aerojustaero 's dump it seems LSP is also active on the org buffer?

**Comment by credmp** [comment]
Just to check back. If I check out `before-save-hook` in an org file:

    (+format-buffer-h
     toc-org-insert-toc
     org-update-parent-todo-statistics
     org-encrypt-entries
     t)

The `+format-buffer-h` will call `format-all-buffer` which will show the same error message.

Removing the `+format-buffer-h` hook removes the error message. This can be tested using the following in `M-:`.

    (remove-hook 'before-save-hook '+format-buffer-h t)

So it seems that the hook should be removed from the org-mode `before-save-hook`.

**Comment by credmp** [comment]
Confirmed that the error is gone when the formatter mode is properly configured:

    (setq +format-on-save-enabled-modes
      '(not emacs-lisp-mode  ; elisp's mechanisms are good enough
            sql-mode         ; sqlformat is currently broken
            tex-mode         ; latexindent is broken
            org-mode
            latex-mode))

**Comment by hlissner** [comment]
As of #4425 this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by hughwilliams94** [comment]
Not sure whether this should be added as a separate issue but `org-journal-mode` is also being affected. This means that when I save an org-journal entry with :crypt: tags autoencryption fails. The change in #4425 does not seem to resolve the org-journal issue.

**Comment by doblak** [comment]
Got the same for `sh-mode`: `Don’t know how to format sh-mode code`

I might have something misconfigured. However adding it to the list of disabled modes enabled ws-butler.
