### ISSUE TITLE
Cannot change font size

### ISSUE THREAD

**Issue by yglukhov** [hlissner/doom-emacs#5146]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

`doom-big-font-mode` and `doom/increase-font-size` should increase font size.

### What actually happened?

`doom-big-font-mode` and `doom/increase-font-size` do not work and print "Cannot change font size" in the Messages buffer.

### Steps to reproduce

- Install fresh doom with clean config
- Press `SPC t b`
- Observe error

### System Information

https://pastebin.com/jj9SC9Sg

**Comment by allumik** [comment]
Same issue, but produces "Wrong type argument: stringp, nil" error for me. Mostly likely this issue started from f408016c6ff6c3fe02f7b43125e6adb587a34bdb.

My font config block:
```elisp
(setq
 default-font "Iosevka Term SS08"
 default-font-size 12.0
 default-nice-size 9.0
 doom-font-increment 1
 doom-font (font-spec :family default-font
                      :size default-font-size)
 doom-variable-pitch-font (font-spec :family "IBM Plex Sans Condensed"
                                     :size default-font-size)
 doom-unicode-font (font-spec :family "IBM Plex Mono"
                              :size default-font-size)
 doom-serif-font (font-spec :family "IBM Plex Serif"
                            :size default-nice-size)
 )
```

**Comment by hlissner** [comment]
Please produce [a backtrace](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error) from errors (as the issue form requested).

**Comment by yglukhov** [comment]
Here's my backtrace
```
Debugger entered--Lisp error: (error "Cannot change font size")
  signal(error ("Cannot change font size"))
  error("Cannot change font size")
  (if (x-list-fonts font) nil (error "Cannot change font size"))
  (if (= orig-size new-size) (message "Could not resize `%s' for some reason" var) (put var 'new-size new-size) (aset dfont xlfd-regexp-pixelsize-subnum (number-to-string new-size)) (aset dfont xlfd-regexp-pointsize-subnum "*") (aset dfont xlfd-regexp-avgwidth-subnum "*") (setq font (x-compose-font-name dfont)) (if (x-list-fonts font) nil (error "Cannot change font size")) (set var font) (setq changed t))
  (let* ((step (if fixed-size-p 0 (* increment doom-font-increment))) (orig-size (string-to-number (aref dfont xlfd-regexp-pixelsize-subnum))) (new-size (if fixed-size-p increment (+ orig-size step)))) (if (> new-size 0) nil (error "`%s' font is too small to be reszied (%d)" var new-size)) (if (= orig-size new-size) (message "Could not resize `%s' for some reason" var) (put var 'new-size new-size) (aset dfont xlfd-regexp-pixelsize-subnum (number-to-string new-size)) (aset dfont xlfd-regexp-pointsize-subnum "*") (aset dfont xlfd-regexp-avgwidth-subnum "*") (setq font (x-compose-font-name dfont)) (if (x-list-fonts font) nil (error "Cannot change font size")) (set var font) (setq changed t)))
  (let* ((orig-font (or (symbol-value var) (face-font face t) (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn ...) (and ... ...)))))) (font (doom--font2xlfd orig-font)) (font (or (and (query-fontset font) (let* ((ascii ...)) (if ascii (nth 2 ascii) font))) font)) (dfont (and (stringp font) (x-decompose-font-name font))) (dfont (let* ((remap-font (and t (alist-get var font-alist))) (remap-xlfd (and remap-font (if ... ... ...)))) (if remap-xlfd (x-decompose-font-name remap-xlfd) dfont)))) (if (get var 'initial-value) nil (put var 'initial-value orig-font)) (if (vectorp dfont) nil (error "Could not decompose %S font: %S" var font)) (let* ((step (if fixed-size-p 0 (* increment doom-font-increment))) (orig-size (string-to-number (aref dfont xlfd-regexp-pixelsize-subnum))) (new-size (if fixed-size-p increment (+ orig-size step)))) (if (> new-size 0) nil (error "`%s' font is too small to be reszied (%d)" var new-size)) (if (= orig-size new-size) (message "Could not resize `%s' for some reason" var) (put var 'new-size new-size) (aset dfont xlfd-regexp-pixelsize-subnum (number-to-string new-size)) (aset dfont xlfd-regexp-pointsize-subnum "*") (aset dfont xlfd-regexp-avgwidth-subnum "*") (setq font (x-compose-font-name dfont)) (if (x-list-fonts font) nil (error "Cannot change font size")) (set var font) (setq changed t))))
  (if (null increment) (if (get var 'initial-value) (progn (set var (get var 'initial-value)) (put var 'new-size nil) (put var 'initial-value nil) (setq changed t))) (let* ((orig-font (or (symbol-value var) (face-font face t) (let ((temp-buffer ...)) (save-current-buffer (set-buffer temp-buffer) (unwind-protect ... ...))))) (font (doom--font2xlfd orig-font)) (font (or (and (query-fontset font) (let* (...) (if ascii ... font))) font)) (dfont (and (stringp font) (x-decompose-font-name font))) (dfont (let* ((remap-font (and t ...)) (remap-xlfd (and remap-font ...))) (if remap-xlfd (x-decompose-font-name remap-xlfd) dfont)))) (if (get var 'initial-value) nil (put var 'initial-value orig-font)) (if (vectorp dfont) nil (error "Could not decompose %S font: %S" var font)) (let* ((step (if fixed-size-p 0 (* increment doom-font-increment))) (orig-size (string-to-number (aref dfont xlfd-regexp-pixelsize-subnum))) (new-size (if fixed-size-p increment (+ orig-size step)))) (if (> new-size 0) nil (error "`%s' font is too small to be reszied (%d)" var new-size)) (if (= orig-size new-size) (message "Could not resize `%s' for some reason" var) (put var 'new-size new-size) (aset dfont xlfd-regexp-pixelsize-subnum (number-to-string new-size)) (aset dfont xlfd-regexp-pointsize-subnum "*") (aset dfont xlfd-regexp-avgwidth-subnum "*") (setq font (x-compose-font-name dfont)) (if (x-list-fonts font) nil (error "Cannot change font size")) (set var font) (setq changed t)))))
  (let* ((face sym) (var (if face (car-safe (prog1 face (setq face (cdr face)))) (signal 'wrong-number-of-arguments (list '(var . face) (length face)))))) (if (null increment) (if (get var 'initial-value) (progn (set var (get var 'initial-value)) (put var 'new-size nil) (put var 'initial-value nil) (setq changed t))) (let* ((orig-font (or (symbol-value var) (face-font face t) (let (...) (save-current-buffer ... ...)))) (font (doom--font2xlfd orig-font)) (font (or (and (query-fontset font) (let* ... ...)) font)) (dfont (and (stringp font) (x-decompose-font-name font))) (dfont (let* ((remap-font ...) (remap-xlfd ...)) (if remap-xlfd (x-decompose-font-name remap-xlfd) dfont)))) (if (get var 'initial-value) nil (put var 'initial-value orig-font)) (if (vectorp dfont) nil (error "Could not decompose %S font: %S" var font)) (let* ((step (if fixed-size-p 0 (* increment doom-font-increment))) (orig-size (string-to-number (aref dfont xlfd-regexp-pixelsize-subnum))) (new-size (if fixed-size-p increment (+ orig-size step)))) (if (> new-size 0) nil (error "`%s' font is too small to be reszied (%d)" var new-size)) (if (= orig-size new-size) (message "Could not resize `%s' for some reason" var) (put var 'new-size new-size) (aset dfont xlfd-regexp-pixelsize-subnum (number-to-string new-size)) (aset dfont xlfd-regexp-pointsize-subnum "*") (aset dfont xlfd-regexp-avgwidth-subnum "*") (setq font (x-compose-font-name dfont)) (if (x-list-fonts font) nil (error "Cannot change font size")) (set var font) (setq changed t))))))
  (let ((sym (car --dolist-tail--))) (let* ((face sym) (var (if face (car-safe (prog1 face (setq face ...))) (signal 'wrong-number-of-arguments (list '... (length face)))))) (if (null increment) (if (get var 'initial-value) (progn (set var (get var 'initial-value)) (put var 'new-size nil) (put var 'initial-value nil) (setq changed t))) (let* ((orig-font (or (symbol-value var) (face-font face t) (let ... ...))) (font (doom--font2xlfd orig-font)) (font (or (and ... ...) font)) (dfont (and (stringp font) (x-decompose-font-name font))) (dfont (let* (... ...) (if remap-xlfd ... dfont)))) (if (get var 'initial-value) nil (put var 'initial-value orig-font)) (if (vectorp dfont) nil (error "Could not decompose %S font: %S" var font)) (let* ((step (if fixed-size-p 0 ...)) (orig-size (string-to-number ...)) (new-size (if fixed-size-p increment ...))) (if (> new-size 0) nil (error "`%s' font is too small to be reszied (%d)" var new-size)) (if (= orig-size new-size) (message "Could not resize `%s' for some reason" var) (put var 'new-size new-size) (aset dfont xlfd-regexp-pixelsize-subnum (number-to-string new-size)) (aset dfont xlfd-regexp-pointsize-subnum "*") (aset dfont xlfd-regexp-avgwidth-subnum "*") (setq font (x-compose-font-name dfont)) (if (x-list-fonts font) nil (error "Cannot change font size")) (set var font) (setq changed t)))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((sym (car --dolist-tail--))) (let* ((face sym) (var (if face (car-safe (prog1 face ...)) (signal 'wrong-number-of-arguments (list ... ...))))) (if (null increment) (if (get var 'initial-value) (progn (set var (get var ...)) (put var 'new-size nil) (put var 'initial-value nil) (setq changed t))) (let* ((orig-font (or ... ... ...)) (font (doom--font2xlfd orig-font)) (font (or ... font)) (dfont (and ... ...)) (dfont (let* ... ...))) (if (get var 'initial-value) nil (put var 'initial-value orig-font)) (if (vectorp dfont) nil (error "Could not decompose %S font: %S" var font)) (let* ((step ...) (orig-size ...) (new-size ...)) (if (> new-size 0) nil (error "`%s' font is too small to be reszied (%d)" var new-size)) (if (= orig-size new-size) (message "Could not resize `%s' for some reason" var) (put var ... new-size) (aset dfont xlfd-regexp-pixelsize-subnum ...) (aset dfont xlfd-regexp-pointsize-subnum "*") (aset dfont xlfd-regexp-avgwidth-subnum "*") (setq font ...) (if ... nil ...) (set var font) (setq changed t)))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((--dolist-tail-- '((doom-font . default) (doom-serif-font . fixed-pitch-serif) (doom-variable-pitch-font . variable-pitch)))) (while --dolist-tail-- (let ((sym (car --dolist-tail--))) (let* ((face sym) (var (if face (car-safe ...) (signal ... ...)))) (if (null increment) (if (get var 'initial-value) (progn (set var ...) (put var ... nil) (put var ... nil) (setq changed t))) (let* ((orig-font ...) (font ...) (font ...) (dfont ...) (dfont ...)) (if (get var ...) nil (put var ... orig-font)) (if (vectorp dfont) nil (error "Could not decompose %S font: %S" var font)) (let* (... ... ...) (if ... nil ...) (if ... ... ... ... ... ... ... ... ... ...))))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (if changed (progn (doom-init-fonts-h 'reload) t)))
  (let (changed) (let ((--dolist-tail-- '((doom-font . default) (doom-serif-font . fixed-pitch-serif) (doom-variable-pitch-font . variable-pitch)))) (while --dolist-tail-- (let ((sym (car --dolist-tail--))) (let* ((face sym) (var (if face ... ...))) (if (null increment) (if (get var ...) (progn ... ... ... ...)) (let* (... ... ... ... ...) (if ... nil ...) (if ... nil ...) (let* ... ... ...)))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (if changed (progn (doom-init-fonts-h 'reload) t))))
  (condition-case e (let (changed) (let ((--dolist-tail-- '((doom-font . default) (doom-serif-font . fixed-pitch-serif) (doom-variable-pitch-font . variable-pitch)))) (while --dolist-tail-- (let ((sym (car --dolist-tail--))) (let* ((face sym) (var ...)) (if (null increment) (if ... ...) (let* ... ... ... ...))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (if changed (progn (doom-init-fonts-h 'reload) t)))) ((debug error) (condition-case nil (progn (doom-adjust-font-size nil)) (error nil)) (signal (car e) (cdr e))))
  doom-adjust-font-size(4)
  (if doom-big-font (doom-adjust-font-size (and doom-big-font-mode (aref (x-decompose-font-name (doom--font2xlfd font)) xlfd-regexp-pixelsize-subnum)) t (list (cons 'doom-font doom-big-font))) (doom-adjust-font-size (if doom-big-font-mode doom-big-font-increment)))
  (let ((last-message (current-message))) (progn (set-default 'doom-big-font-mode (if (eq arg 'toggle) (not (default-value 'doom-big-font-mode)) (> (prefix-numeric-value arg) 0)))) (if doom-big-font (doom-adjust-font-size (and doom-big-font-mode (aref (x-decompose-font-name (doom--font2xlfd font)) xlfd-regexp-pixelsize-subnum)) t (list (cons 'doom-font doom-big-font))) (doom-adjust-font-size (if doom-big-font-mode doom-big-font-increment))) (run-hooks 'doom-big-font-mode-hook (if (default-value 'doom-big-font-mode) 'doom-big-font-mode-on-hook 'doom-big-font-mode-off-hook)) (if (called-interactively-p 'any) (progn (customize-mark-as-set 'doom-big-font-mode) (if (and (current-message) (not (equal last-message (current-message)))) nil (let ((local "")) (message "Doom-Big-Font mode %sabled%s" (if (default-value ...) "en" "dis") local))))))
  doom-big-font-mode(toggle)
  #<subr funcall-interactively>(doom-big-font-mode toggle)
  apply(#<subr funcall-interactively> (doom-big-font-mode toggle))
  funcall-interactively(doom-big-font-mode toggle)
  #<subr call-interactively>(doom-big-font-mode nil nil)
  apply(#<subr call-interactively> (doom-big-font-mode nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> doom-big-font-mode nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (doom-big-font-mode nil nil))
  call-interactively(doom-big-font-mode nil nil)
  command-execute(doom-big-font-mode)
```

**Comment by hlissner** [comment]
As of c34ed0d this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by yglukhov** [comment]
It works now, thank you!

**Comment by allumik** [comment]
Thank you! 

Resizing works now, but doing so it changes the font too if you have set a different font for the modeline and/or modified the face-attributes to varying weighting.

For example I have *Lekton thin* for the inactive modeline - when resizing the fonts, then the normal font *Iosevka* gets replaced with the modeline font. In this case I have not defined the weighting of the normal font yet. 

When i define the font weighing for the normal font with `(font-spec :weight 'regular)`, then the font does not change as intended, but the normal font turns into *italics* when resizing.

As it does not produce errors, then I don't know how to debug this. The relevant parts of my `config.el` are below. I will try to reproduce this issue with a minimal config in the next few days if I have time. I suspect the main culprit is defining the face-attributes in the private config. Maybe the `doom--normalize-font` function applying the manually configured font specs to the whole font, but that is just a guess.

<details>
<summary>Relevant config part:</summary>

```elisp
;; *** FONT ***
(setq
 default-font-size 12.0
 default-nice-size 9.0
 doom-font-increment 1
 doom-font (font-spec :family "Iosevka Term SS08"
                      :size default-font-size
                      :weight 'regular)
 doom-variable-pitch-font (font-spec :family "IBM Plex Sans Condensed"
                                     :size default-font-size)
 doom-big-font (font-spec :family "IBM Plex Mono"
                          :size (+ default-font-size 2))
 doom-unicode-font (font-spec :family "IBM Plex Mono"
                              :size default-font-size)
 doom-serif-font (font-spec :family "IBM Plex Serif"
                            :size default-nice-size)
 )


 ;; *** Frame settings ***
(setq
 ;; frame size
 initial-frame-alist '((internal-border-width . 8))
 default-frame-alist '((internal-border-width . 8))
 ;; space between windows
 window-divider-default-right-width 8
 window-divider-default-bottom-width 4
 window-divider-default-places t  ;; put 'right/bottom-only if appropriate
 )

 ;; *** multiedit & mc ***
(setq
 evil-multiedit-follow-matches t
 evil-multiedit-store-in-search-history t
 )

 ;; *** Modeline settings ***
(setq
 doom-modeline-height 20 ; font size + 6
 doom-modeline-bar-width 4
 doom-modeline-icon nil ; "nil" if the all-the-icons installer fails
 doom-modeline-enable-word-count nil
 doom-modeline-modal-icon t
 doom-modeline-major-mode-color-icon t
 )

 ;; general stuff
(setq
 browse-url-generic-program "xdg-open" ;; NOTE when using mac, change it
 browse-url-browser-function 'browse-url-generic
 remote-shell-program "/usr/bin/bash"
 shell-file-name "/bin/zsh"
 counsel-search-engine 'google
 x-stretch-cursor t

 custom-safe-themes t
 org-startup-folded t
 +zen-text-scale 1
 evil-snipe-scope 'visible
 display-line-numbers-type nil ;; 'relative
 global-git-gutter-mode t
 ;; vc-handled-backends (remove 'Git vc-handled-backends)
 remote-file-name-inhibit-cache nil
 vc-ignore-dir-regexp
      (format "%s\\|%s"
                    vc-ignore-dir-regexp
                    tramp-file-name-regexp)
 tramp-verbose 1
 comint-scroll-to-bottom-on-input 'others
 comint-scroll-to-bottom-on-output 'others
 ;; recentf-auto-cleanup 'never
 delete-by-moving-to-trash t
 golden-ratio-auto-scale t
 ;; prescient-sort-length-enable nil
 ;; prescient-persist-mode 1

 ;; location for auto-theme
 calendar-location-name "Tartu, Estonia"
 calendar-latitude 58.3604
 calendar-longitude 26.7214
 )


;; *** Jellybeans theme ***
(defun load-jbeans-w-defaults ()
  (load-theme 'jbeans)
  (set-face-attribute 'italic nil :slant 'italic :underline nil)
  (set-face-attribute 'bold-italic nil
                      :inherit '(bold italic) :underline nil)
  (set-face-attribute 'bold-italic nil
                      :inherit '(bold italic) :underline nil)

  (after! org
    (set-face-attribute 'org-ellipsis nil :underline nil)
    (set-face-attribute 'org-quote nil :slant 'italic :extend t)
    )

  (after! dired
    (use-package dired-rainbow
      :config
      (progn
        (dired-rainbow-define vc "dodgerblue" ("git" "gitignore" "gitattributes" "gitmodules"))
        (dired-rainbow-define compressed "darkorange" ("7z" "zip" "bz2" "tgz" "txz" "gz" "xz" "z" "Z" "jar" "war" "ear" "rar" "sar" "xpi" "apk" "xz" "tar"))
        (dired-rainbow-define-chmod executable-unix "darkseagreen" "-[rw-]+x.*")
        (dired-rainbow-define-chmod directory (:bold t :foreground "peru") "drwxrwxrwx")))
    )
  )

(load-jbeans-w-defaults)


;; *** COSMETICS ***
(use-package rainbow-mode ;; color hex highlighting
 :hook '(prog-mode text-mode))

;; have tighter text, especially in programming languages
(add-hook! '(text-mode-hook prog-mode-hook)
           (setq line-spacing 0))

;; Enable variating background colors
(solaire-global-mode +1)
;; (solaire-mode-swap-bg)
;; Enable flashing mode-line on errors
(doom-themes-visual-bell-config)

;; force the theme to use italics for some elements
(set-face-attribute 'font-lock-comment-face nil
                    :slant 'italic)
(set-face-attribute 'font-lock-function-name-face nil
                    :bold t)
(set-face-attribute 'mode-line nil :family "Lekton Nerd Font Mono" :weight 'regular)
(set-face-attribute 'mode-line-inactive nil :family "Lekton Nerd Font Mono" :weight 'thin)

;; make the window divider dissappear
(defun get-fringe-bg-color ()
  (face-attribute 'fringe :background))

(set-face-attribute 'window-divider nil
                    :foreground (get-fringe-bg-color))
(set-face-attribute 'window-divider-first-pixel nil
                    :foreground (get-fringe-bg-color))
(set-face-attribute 'window-divider-last-pixel nil
                    :foreground (get-fringe-bg-color))
;; (set-face-attribute 'posframe- nil
;;                     :foreground (get-fringe-bg-color))
```

**Comment by paolo** [comment]
I'm still seeing this issue, I tried to debug it myself and I was able to identify that the problem was that `orig-size` and `new-size` both had the same value, the one from **doom-big-font**.
So I changed the definition of orig-size like so:
```diff
-                       (orig-size (font-get dfont :size))
+                       (orig-size (font-get font :size))
```

**Comment by cosmicz** [comment]
@paolo's fix worked for me. Thank you

**Comment by hlissner** [comment]
As of bafb392, @allumik's issue should be fixed.
