### ISSUE TITLE
`doom/reload-theme` reloads `doom-theme`, not the current theme

### ISSUE THREAD

**Issue by dschrempf** [hlissner/doom-emacs#5539]
### What did you expect to happen?

`doom/reload-theme` should reload the current theme.

### What actually happened?

`doom/reload-theme` reloads the theme stored in `doom-theme`, which can be different from the current theme. Afterwards it reports that it has reloaded the current theme, although it actually reloaded `doom-theme`.

### Describe your attempts to resolve the issue

`doom/reload-theme` is implemented like so:
```
;;;###autoload
(defun doom/reload-theme ()
  "Reload the current color theme."
  (interactive)
  (let ((themes (copy-sequence custom-enabled-themes)))
    (load-theme doom-theme t)
    (doom/reload-font)
    (message "%s %s"
             (propertize "Reloaded themes:" 'face 'bold)
             (mapconcat #'prin1-to-string themes ", "))))
```

### Steps to reproduce

```lisp
(setq doom-theme "doom-one")
(consult-theme) ;; choose "doom-one-light"
(doom/reload-theme)
```

### System Information

-

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by dschrempf** [comment]
Thank you, the fix works perfectly!

**Comment by andrewjrae** [comment]
I seem to be having a similar issue, even after updating to this fix. However, it seems as though doom is attempting to reload the correct theme, as the messages prints `Reloaded 1 theme: doom-one`, but the result is an incorrect theme.

Interestingly this seems to happen any time you attempt to load a theme again. Calling `(consult-theme)` (`SPC h t`), and picking a new theme works the first time, but fails if you either reload, or switch to another theme and back. The incorrect theme it loads seems to always be the same, and it looks to me like it's the default emacs theme.

I also tried switching back to ivy (from vertico) with counsel's theme loading, however that did not fix things.

This is with 28.05 native comp.

**Comment by bricewge** [comment]
That's because `consult-theme` uses [`enable-theme`](https://github.com/minad/consult/blob/main/consult.el#L3736) instead of `load-theme`. Commit 087a13523eb698e2f5816d941c80114f13ca5e09 description state it doesn't fix `consult-theme` unfortunately.

This bug should be reopen, or a new one created, to track this bug.
