### ISSUE TITLE
In doom scratch buffer or popup buffer, typing enter in org-mode's src block will unexpectly delete window 

### ISSUE THREAD

**Issue by chaoyi** [hlissner/doom-emacs#6061]
### What did you expect to happen?

popup buffer window remains open

### What actually happened?

popup buffer window deleted unexpectedly
[backtrace](https://pastebin.com/raw/b1gtzcS6)

### Steps to reproduce

1. doom/open-scratch-buffer
2. change major mode to org-mode
3. create a src block
```
#+begin_src bash
#+end_src
```
4. type enter inside src block
5. popup buffer is closed

### System Information

https://pastebin.com/raw/iFtCw35T

**Comment by hlissner** [comment]
I was able to reproduce this, and isolate it to the `org-babel-do-in-edit-buffer` macro; it seems to be an upstream bug and should be reported to org.

In any case, I've deployed a temporary (and messy) fix in 9217bb8, which should resolve it until it can be addressed upstream. Let me know if the problem returns and I'll reopen the issue. Thanks for bringing it to my attention!

**Comment by chaoyi** [comment]
Thanks very much!

**Comment by marcinkoziej** [comment]
Hi @chaoyi - was this submitted to upstream in the end?
I'm testing doom with emacs29 and run into a problem with the hack, I get an error when using `org-clock-mode`

```
Debugger entered--Lisp error: (invalid-function org-element-with-disabled-cache)
  org-element-with-disabled-cache((clock (:status running :value (timestamp (:type inactive :raw-value "[2023-03-09 Thu 15:33]" :year-start 2023 :month-start 3 :day-start 9 :hour-start 15 :minute-start 33 :year-end 2023 :month-end 3 :day-end 9 :hour-end 15 :minute-end 33 :begin 3656 :end 3678 :post-blank 0)) :duration nil :begin 3649 :end 3679 :post-blank 0 :post-affiliated 3649 :mode nil :granularity element :parent (drawer (:begin 3639 :end 3685 :drawer-name "LOGBOOK" :contents-begin 3649 :contents-end 3679 :post-blank 0 :post-affiliated 3639 :mode planning :granularity element :parent (section (:begin 3639 :end 3685 :contents-begin 3639 :contents-end 3685 :robust-begin 3639 :robust-end 3683 :post-blank 0 :post-affiliated 3639 :mode section :granularity element :parent (headline ...))))))))
  org-element-at-point-no-context()
  #<subr org-indent-line>()
  apply(#<subr org-indent-line> nil)
  (progn (apply fn args))
  (unwind-protect (progn (apply fn args)) (set-window-configuration wconfig))
  (let ((wconfig (current-window-configuration))) (unwind-protect (progn (apply fn args)) (set-window-configuration wconfig)))
  +org-fix-window-excursions-a(#<subr org-indent-line>)
  apply(+org-fix-window-excursions-a #<subr org-indent-line> nil)
  org-indent-line()
  #<subr org-clock-in>(nil)
  apply(#<subr org-clock-in> nil)
  org-clock-in(nil)
  funcall-interactively(org-clock-in nil)
  call-interactively(org-clock-in nil nil)
  command-execute(org-clock-in)
```

Removing the advice in `modules/lang/org/config.el` fixes the problem – but this is not ideal it the bug is still present upstream.
Is it?
